import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const FundingCalculator: React.FC = () => {
  const [companyName, setCompanyName] = useState('');
  const [inputs, setInputs] = useState({
    fundingNeeded: 500000,
    preMoneyValuation: 2000000,
    investorType: 'angel'
  });
  const [result, setResult] = useState('');

  const calculate = () => {
    const name = companyName || 'Company';
    const { fundingNeeded, preMoneyValuation } = inputs;
    
    const postMoneyValuation = preMoneyValuation + fundingNeeded;
    const equityGiven = (fundingNeeded / postMoneyValuation) * 100;
    const founderEquity = 100 - equityGiven;
    
    // Investor return scenarios
    const exitScenarios = [
      { exit: 5000000, label: '$5M Exit' },
      { exit: 10000000, label: '$10M Exit' },
      { exit: 25000000, label: '$25M Exit' },
      { exit: 50000000, label: '$50M Exit' },
      { exit: 100000000, label: '$100M Exit' }
    ];

    const scenarioRows = exitScenarios.map(s => {
      const investorReturn = s.exit * (equityGiven / 100);
      const founderReturn = s.exit * (founderEquity / 100);
      const investorMultiple = investorReturn / fundingNeeded;
      return `| ${s.label} | $${investorReturn.toLocaleString()} (${investorMultiple.toFixed(1)}x) | $${founderReturn.toLocaleString()} |`;
    }).join('\n');

    const output = `
# FUNDING ANALYSIS
## ${name.toUpperCase()}

---

## DEAL TERMS

| Metric | Value |
|--------|-------|
| Funding Needed | $${fundingNeeded.toLocaleString()} |
| Pre-Money Valuation | $${preMoneyValuation.toLocaleString()} |
| Post-Money Valuation | $${postMoneyValuation.toLocaleString()} |

---

## EQUITY BREAKDOWN

| Party | Equity | Value |
|-------|--------|-------|
| **Founders** | ${founderEquity.toFixed(1)}% | $${(preMoneyValuation * founderEquity / 100).toLocaleString()} |
| **Investors** | ${equityGiven.toFixed(1)}% | $${fundingNeeded.toLocaleString()} |
| **Total** | 100% | $${postMoneyValuation.toLocaleString()} |

---

## EXIT SCENARIOS

| Exit Value | Investor Return | Founder Return |
|------------|-----------------|----------------|
${scenarioRows}

---

## DILUTION ANALYSIS

### Future Funding Rounds (Estimated)

| Round | Funding | Pre-Money | Your Equity After |
|-------|---------|-----------|-------------------|
| Seed (Current) | $${fundingNeeded.toLocaleString()} | $${preMoneyValuation.toLocaleString()} | ${founderEquity.toFixed(1)}% |
| Series A | $2,000,000 | $8,000,000 | ${(founderEquity * 0.8).toFixed(1)}% |
| Series B | $10,000,000 | $40,000,000 | ${(founderEquity * 0.8 * 0.8).toFixed(1)}% |

---

## KEY INSIGHTS

- **Investor Ownership:** ${equityGiven.toFixed(1)}%
- **Founder Ownership:** ${founderEquity.toFixed(1)}%
- **Money Multiple for Investors at $50M exit:** ${(50000000 * equityGiven / 100 / fundingNeeded).toFixed(1)}x
- **Your Proceeds at $50M exit:** $${(50000000 * founderEquity / 100).toLocaleString()}

---

## RECOMMENDATIONS

1. **Valuation:** Ensure valuation is realistic for your stage
2. **Equity:** Consider keeping 10-20% for employee option pool
3. **Terms:** Look beyond valuation at liquidation preferences, board seats
4. **Dilution:** Plan for 2-3 rounds before profitability
5. **Exit Strategy:** Understand what exit value creates returns for all parties

---

*Generated by Abetworks Funding Calculator*
`.trim();

    setResult(output);
  };

  return (
    <ToolWrapper
      title="Funding Calculator"
      description="Calculate equity dilution and investor returns for your funding round"
      icon="💰"
      inputValue={companyName}
      outputValue={result}
      outputLabel="Funding Analysis"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-funding-analysis.md"
    >
      <div className="row g-3">
        <div className="col-md-6">
          <label className="form-label">Company Name</label>
          <input type="text" className="form-control" value={companyName} onChange={(e) => setCompanyName(e.target.value)} />
        </div>
        <div className="col-md-3">
          <label className="form-label">Funding Needed ($)</label>
          <input type="number" className="form-control" value={inputs.fundingNeeded} onChange={(e) => setInputs({ ...inputs, fundingNeeded: parseInt(e.target.value) || 0 })} />
        </div>
        <div className="col-md-3">
          <label className="form-label">Pre-Money Valuation ($)</label>
          <input type="number" className="form-control" value={inputs.preMoneyValuation} onChange={(e) => setInputs({ ...inputs, preMoneyValuation: parseInt(e.target.value) || 0 })} />
        </div>
      </div>
      <div className="d-flex gap-3 mt-4">
        <button className="btn btn-primary btn-lg" onClick={calculate}>💰 Calculate Funding</button>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Funding Calculator" compact /></div>
    </ToolWrapper>
  );
};

export default FundingCalculator;
