import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const ClientOnboardingChecklist: React.FC = () => {
  const [clientName, setClientName] = useState('');
  const [checklist, setChecklist] = useState('');

  const generate = () => {
    const client = clientName || 'Client';
    const output = `
# CLIENT ONBOARDING CHECKLIST
## ${client}

---

## PHASE 1: PRE-KICKOFF (Week 1)

### Documentation
- [ ] Signed contract received
- [ ] Deposit/payment received
- [ ] NDA signed (if applicable)
- [ ] Project scope confirmed

### Access & Credentials
- [ ] Client portal access set up
- [ ] Communication channels established
- [ ] File sharing access granted
- [ ] Brand assets received

### Team Preparation
- [ ] Internal team briefing scheduled
- [ ] Roles and responsibilities assigned
- [ ] Project timeline reviewed
- [ ] Risk assessment completed

---

## PHASE 2: DISCOVERY (Week 1-2)

### Client Interviews
- [ ] Stakeholder interviews scheduled
- [ ] User research planned
- [ ] Competitor analysis initiated
- [ ] Current state assessment

### Requirements Gathering
- [ ] Functional requirements documented
- [ ] Technical requirements reviewed
- [ ] Success metrics defined
- [ ] Constraints identified

### Strategy Development
- [ ] Project strategy documented
- [ ] Approach validated with client
- [ ] Timeline confirmed
- [ ] Resource allocation finalized

---

## PHASE 3: KICKOFF (Week 2)

### Kickoff Meeting
- [ ] Agenda prepared
- [ ] All stakeholders invited
- [ ] Presentation deck ready
- [ ] Meeting recorded

### Post-Kickoff
- [ ] Meeting notes distributed
- [ ] Action items assigned
- [ ] Next steps confirmed
- [ ] Communication cadence established

---

## PHASE 4: EXECUTION SETUP (Week 2-3)

### Project Setup
- [ ] Project management tool configured
- [ ] Task breakdown created
- [ ] Milestones defined
- [ ] Dependencies mapped

### Communication Plan
- [ ] Weekly status meetings scheduled
- [ ] Reporting template prepared
- [ ] Escalation path defined
- [ ] Feedback loops established

### Quality Assurance
- [ ] QA checklist created
- [ ] Testing plan developed
- [ ] Acceptance criteria defined
- [ ] Review process documented

---

## PHASE 5: ONGOING MANAGEMENT

### Weekly Activities
- [ ] Status report sent
- [ ] Progress tracking updated
- [ ] Blockers addressed
- [ ] Client check-in completed

### Monthly Activities
- [ ] Monthly review meeting
- [ ] KPI dashboard updated
- [ ] Budget vs. actual reviewed
- [ ] Scope change assessment

---

## CLIENT INFORMATION

| Field | Details |
|-------|---------|
| Company | ${client} |
| Primary Contact | [Name, Email, Phone] |
| Secondary Contact | [Name, Email, Phone] |
| Time Zone | [Time Zone] |
| Preferred Communication | [Email/Slack/Phone] |

---

## SUCCESS CRITERIA

- [ ] Client satisfaction score > 8/10
- [ ] On-time delivery rate > 90%
- [ ] Budget variance < 10%
- [ ] Response time < 24 hours
- [ ] Zero critical issues

---

## NOTES

[Add any client-specific notes, preferences, or special considerations]

---

*Generated by Abetworks Client Onboarding Checklist*
`.trim();
    setChecklist(output);
  };

  return (
    <ToolWrapper title="Client Onboarding Checklist" description="Ensure smooth client onboarding with this comprehensive checklist" icon="✅" inputValue={clientName} outputValue={checklist} outputLabel="Onboarding Checklist" showCopy={true} showDownload={true} downloadFilename="abetworks-client-onboarding.md">
      <div className="row g-3">
        <div className="col-md-6"><label className="form-label">Client/Company Name</label><input type="text" className="form-control" value={clientName} onChange={(e) => setClientName(e.target.value)} placeholder="Client name" /></div>
        <div className="col-12"><p className="text-muted">Generate a comprehensive client onboarding checklist customized for your new client.</p></div>
        <div className="col-12"><button className="btn btn-primary btn-lg" onClick={generate}>✅ Generate Checklist</button></div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Client Onboarding Checklist" compact /></div>
    </ToolWrapper>
  );
};

export default ClientOnboardingChecklist;
