import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

const ContractTemplateGenerator: React.FC = () => {
  const [data, setData] = useState({
    freelancerName: '', freelancerEmail: '', freelancerAddress: '',
    clientName: '', clientEmail: '', clientAddress: '',
    projectDescription: '', startDate: '', endDate: '',
    paymentAmount: '', paymentTerms: '50% upfront, 50% on completion',
    revisions: '2', terminationNotice: '14'
  });
  const [contract, setContract] = useState('');

  const generate = () => {
    const output = `
# FREELANCE SERVICE AGREEMENT

---

## PARTIES

This Freelance Service Agreement ("Agreement") is entered into on ${new Date().toLocaleDateString()} by and between:

**Freelancer:**
${data.freelancerName || '[Freelancer Name]'}
${data.freelancerEmail || '[Email]'}
${data.freelancerAddress || '[Address]'}

**Client:**
${data.clientName || '[Client Name]'}
${data.clientEmail || '[Email]'}
${data.clientAddress || '[Address]'}

---

## 1. SCOPE OF WORK

The Freelancer agrees to provide the following services to the Client:

${data.projectDescription || '[Description of services to be provided]'}

---

## 2. PROJECT TIMELINE

- **Start Date:** ${data.startDate || '[Date]'}
- **End Date:** ${data.endDate || '[Date]'}
- **Estimated Duration:** As specified in the project scope

---

## 3. COMPENSATION

### Payment Terms
- **Total Project Fee:** $${data.paymentAmount || '[Amount]'}
- **Payment Schedule:** ${data.paymentTerms}
- **Late Payment Fee:** 1.5% per month on overdue amounts

### Payment Methods
Payment shall be made via: [Bank Transfer/PayPal/Check/Other]

---

## 4. REVISIONS

The project includes **${data.revisions} rounds of revisions**. Additional revisions will be billed at $[rate]/hour.

---

## 5. INTELLECTUAL PROPERTY

Upon full payment, the Client shall own all rights, title, and interest in the final deliverables. The Freelancer retains the right to display the work in their portfolio.

---

## 6. CONFIDENTIALITY

Both parties agree to keep all proprietary information confidential and not disclose it to third parties without written consent.

---

## 7. TERMINATION

Either party may terminate this agreement with **${data.terminationNotice} days** written notice. In case of termination:
- Client pays for work completed up to termination date
- Freelancer delivers all completed work
- Any unused retainer is refunded

---

## 8. INDEPENDENT CONTRACTOR

The Freelancer is an independent contractor, not an employee. The Freelancer is responsible for their own taxes, insurance, and benefits.

---

## 9. LIABILITY

The Freelancer's liability is limited to the total project fee. The Freelancer is not liable for indirect, incidental, or consequential damages.

---

## 10. DISPUTE RESOLUTION

Any disputes arising from this agreement shall be resolved through good-faith negotiation. If unresolved, disputes shall be governed by the laws of [Jurisdiction].

---

## 11. ENTIRE AGREEMENT

This Agreement constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, or agreements.

---

## SIGNATURES

**Freelancer:**

Signature: _________________________

Name: ${data.freelancerName || '[Name]'}

Date: _________________________

---

**Client:**

Signature: _________________________

Name: ${data.clientName || '[Name]'}

Date: _________________________

---

*Generated by Abetworks Contract Template Generator*

**Disclaimer:** This is a template and should be reviewed by a legal professional before use.
`.trim();

    setContract(output);
  };

  const downloadPDF = async () => {
    const template = document.getElementById('contract-template');
    if (!template) return;
    template.style.display = 'block';
    try {
      const canvas = await html2canvas(template, { scale: 2 });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      // If height > page height, we'd ideally paginate, but for simplicity we rely on standard contract lengths or scale to fit
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      const safeClient = (data.clientName || 'client').replace(/[^a-z0-9]/gi, '-');
      pdf.save(`abetworks-contract-${safeClient}.pdf`);
    } finally {
      template.style.display = 'none';
    }
  };

  const downloadWord = () => {
    const template = document.getElementById('contract-template');
    if (!template) return;
    const header = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>Export HTML to Word</title></head><body>";
    const footer = "</body></html>";
    const sourceHTML = header + template.innerHTML + footer;
    const source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(sourceHTML);
    const fileDownload = document.createElement("a");
    document.body.appendChild(fileDownload);
    fileDownload.href = source;
    const safeClient = (data.clientName || 'client').replace(/[^a-z0-9]/gi, '-');
    fileDownload.download = `abetworks-contract-${safeClient}.doc`;
    fileDownload.click();
    document.body.removeChild(fileDownload);
  };

  return (
    <ToolWrapper
      title="Freelance Contract Template Generator"
      description="Create a professional freelance service agreement"
      icon="📋"
      inputValue={data.freelancerName}
      outputValue={contract}
      outputLabel="Contract Template"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-freelance-contract.md"
    >
      <div className="row g-3 mb-4">
        <div className="col-md-6">
          <h6 className="mb-2">Freelancer Details</h6>
          <input type="text" className="form-control mb-2" placeholder="Your Name" value={data.freelancerName} onChange={(e) => setData({ ...data, freelancerName: e.target.value })} />
          <input type="email" className="form-control mb-2" placeholder="Your Email" value={data.freelancerEmail} onChange={(e) => setData({ ...data, freelancerEmail: e.target.value })} />
          <textarea className="form-control" placeholder="Your Address" rows={2} value={data.freelancerAddress} onChange={(e) => setData({ ...data, freelancerAddress: e.target.value })} />
        </div>
        <div className="col-md-6">
          <h6 className="mb-2">Client Details</h6>
          <input type="text" className="form-control mb-2" placeholder="Client Name" value={data.clientName} onChange={(e) => setData({ ...data, clientName: e.target.value })} />
          <input type="email" className="form-control mb-2" placeholder="Client Email" value={data.clientEmail} onChange={(e) => setData({ ...data, clientEmail: e.target.value })} />
          <textarea className="form-control" placeholder="Client Address" rows={2} value={data.clientAddress} onChange={(e) => setData({ ...data, clientAddress: e.target.value })} />
        </div>
      </div>

      <div className="row g-3 mb-4">
        <div className="col-12">
          <label className="form-label">Project Description *</label>
          <textarea className="form-control" rows={3} value={data.projectDescription} onChange={(e) => setData({ ...data, projectDescription: e.target.value })} placeholder="Describe the services you'll provide..." />
        </div>
        <div className="col-md-4">
          <label className="form-label">Start Date</label>
          <input type="date" className="form-control" value={data.startDate} onChange={(e) => setData({ ...data, startDate: e.target.value })} />
        </div>
        <div className="col-md-4">
          <label className="form-label">End Date</label>
          <input type="date" className="form-control" value={data.endDate} onChange={(e) => setData({ ...data, endDate: e.target.value })} />
        </div>
        <div className="col-md-4">
          <label className="form-label">Payment Amount ($)</label>
          <input type="number" className="form-control" value={data.paymentAmount} onChange={(e) => setData({ ...data, paymentAmount: e.target.value })} />
        </div>
        <div className="col-md-6">
          <label className="form-label">Payment Terms</label>
          <input type="text" className="form-control" value={data.paymentTerms} onChange={(e) => setData({ ...data, paymentTerms: e.target.value })} placeholder="e.g., 50% upfront, 50% on completion" />
        </div>
        <div className="col-md-3">
          <label className="form-label">Revisions Included</label>
          <input type="number" className="form-control" value={data.revisions} onChange={(e) => setData({ ...data, revisions: e.target.value })} />
        </div>
        <div className="col-md-3">
          <label className="form-label">Termination Notice (days)</label>
          <input type="number" className="form-control" value={data.terminationNotice} onChange={(e) => setData({ ...data, terminationNotice: e.target.value })} />
        </div>
      </div>

      <div className="d-flex gap-3 flex-wrap">
        <button className="btn btn-outline-primary" onClick={generate}>📋 Generate Text Version</button>
        <button className="btn btn-danger" onClick={downloadPDF}>📄 Download PDF</button>
        <button className="btn btn-primary" onClick={downloadWord}>📝 Download Word</button>
      </div>

      {/* Hidden visual template for PDF/Word export */}
      <div id="contract-template" style={{ display: 'none', padding: '50px', background: '#fff', color: '#000', fontFamily: '"Times New Roman", Times, serif', fontSize: '16px', width: '800px', lineHeight: '1.8' }}>
        <h1 style={{ textAlign: 'center', textTransform: 'uppercase', marginBottom: '40px', fontSize: '24px', letterSpacing: '1px' }}>Freelance Service Agreement</h1>
        
        <p>This Freelance Service Agreement ("Agreement") is entered into on <strong>{new Date().toLocaleDateString()}</strong> by and between:</p>
        
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '30px', padding: '20px', border: '1px solid #ccc' }}>
          <div style={{ flex: 1 }}>
            <strong>Freelancer:</strong><br/>
            {data.freelancerName || '[Freelancer Name]'}<br/>
            {data.freelancerEmail}<br/>
            {data.freelancerAddress}
          </div>
          <div style={{ flex: 1 }}>
            <strong>Client:</strong><br/>
            {data.clientName || '[Client Name]'}<br/>
            {data.clientEmail}<br/>
            {data.clientAddress}
          </div>
        </div>

        <h2 style={{ fontSize: '18px', borderBottom: '1px solid #000', paddingBottom: '5px', marginTop: '30px' }}>1. Scope of Work</h2>
        <p>The Freelancer agrees to provide the following services to the Client:</p>
        <p style={{ whiteSpace: 'pre-wrap', paddingLeft: '20px' }}>{data.projectDescription || '[Description of services]'}</p>

        <h2 style={{ fontSize: '18px', borderBottom: '1px solid #000', paddingBottom: '5px', marginTop: '30px' }}>2. Project Timeline</h2>
        <ul style={{ paddingLeft: '40px' }}>
          <li><strong>Start Date:</strong> {data.startDate || '[Date]'}</li>
          <li><strong>End Date:</strong> {data.endDate || '[Date]'}</li>
        </ul>

        <h2 style={{ fontSize: '18px', borderBottom: '1px solid #000', paddingBottom: '5px', marginTop: '30px' }}>3. Compensation & Payment</h2>
        <ul style={{ paddingLeft: '40px' }}>
          <li><strong>Total Project Fee:</strong> ${data.paymentAmount || '[Amount]'}</li>
          <li><strong>Payment Schedule:</strong> {data.paymentTerms}</li>
        </ul>

        <h2 style={{ fontSize: '18px', borderBottom: '1px solid #000', paddingBottom: '5px', marginTop: '30px' }}>4. Additional Terms</h2>
        <p>The project includes <strong>{data.revisions}</strong> rounds of revisions. Either party may terminate this agreement with <strong>{data.terminationNotice}</strong> days written notice. The Freelancer is an independent contractor and not an employee of the Client.</p>

        <div style={{ marginTop: '60px', display: 'flex', justifyContent: 'space-between' }}>
          <div style={{ width: '45%' }}>
            <p style={{ margin: 0 }}><strong>Freelancer Signature:</strong></p>
            <div style={{ borderBottom: '1px solid #000', height: '40px', marginBottom: '10px' }}></div>
            <p style={{ margin: 0 }}>Name: {data.freelancerName || '[Name]'}</p>
            <p style={{ margin: 0 }}>Date: _________________</p>
          </div>
          <div style={{ width: '45%' }}>
            <p style={{ margin: 0 }}><strong>Client Signature:</strong></p>
            <div style={{ borderBottom: '1px solid #000', height: '40px', marginBottom: '10px' }}></div>
            <p style={{ margin: 0 }}>Name: {data.clientName || '[Name]'}</p>
            <p style={{ margin: 0 }}>Date: _________________</p>
          </div>
        </div>
        
        <p style={{ fontSize: '12px', textAlign: 'center', marginTop: '60px', color: '#666' }}>Disclaimer: This is a template generated by Abetworks and should be reviewed by a legal professional before use.</p>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Contract Template Generator" compact /></div>
    </ToolWrapper>
  );
};

export default ContractTemplateGenerator;
