import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

// Generic template generator for remaining freelancer tools
const FreelancerToolTemplate: React.FC<{ toolName: string; icon: string; description: string; generateContent: (data: any) => string }> = ({ toolName, icon, description, generateContent }) => {
  const [data, setData] = useState<Record<string, any>>({});
  const [output, setOutput] = useState('');

  const generate = () => {
    const content = generateContent(data);
    setOutput(content);
  };

  return (
    <ToolWrapper title={toolName} description={description} icon={icon} inputValue="" outputValue={output} outputLabel="Output" showCopy={true} showDownload={true} downloadFilename={`abetworks-${toolName.toLowerCase().replace(/\s/g, '-')}.md`}>
      <div className="mb-3">
        <p className="text-muted">Configure your {toolName.toLowerCase()} and click generate.</p>
      </div>
      <button className="btn btn-primary btn-lg" onClick={generate}>{icon} Generate</button>
      <div className="mt-4"><LeadCaptureForm toolName={toolName} compact /></div>
    </ToolWrapper>
  );
};

// Time Tracking Calculator
const TimeTrackingCalculator: React.FC = () => {
  const [projects, setProjects] = useState([{ name: '', hours: 0, rate: 0 }]);
  const [result, setResult] = useState('');

  const addProject = () => setProjects([...projects, { name: '', hours: 0, rate: 0 }]);
  const removeProject = (idx: number) => projects.length > 1 && setProjects(projects.filter((_, i) => i !== idx));
  const updateProject = (idx: number, field: string, value: string | number) => {
    const updated = [...projects];
    (updated[idx] as any)[field] = value;
    setProjects(updated);
  };

  const calculate = () => {
    const totalHours = projects.reduce((sum, p) => sum + (p.hours || 0), 0);
    const totalEarnings = projects.reduce((sum, p) => sum + ((p.hours || 0) * (p.rate || 0)), 0);
    const avgRate = totalHours > 0 ? totalEarnings / totalHours : 0;

    const output = `
# TIME TRACKING SUMMARY

---

## PROJECT BREAKDOWN

| Project | Hours | Rate | Earnings |
|---------|-------|------|----------|
${projects.map(p => `| ${p.name || 'Unnamed'} | ${p.hours} | $${p.rate} | $${(p.hours * p.rate).toFixed(2)} |`).join('\n')}

---

## SUMMARY

| Metric | Value |
|--------|-------|
| Total Hours | ${totalHours} |
| Total Earnings | $${totalEarnings.toFixed(2)} |
| Average Rate | $${avgRate.toFixed(2)}/hr |

---

*Generated by Abetworks Time Tracking Calculator*
`.trim();
    setResult(output);
  };

  return (
    <ToolWrapper title="Time Tracking Calculator" description="Track time and earnings across multiple projects" icon="⏱️" inputValue="" outputValue={result} outputLabel="Time Summary" showCopy={true} showDownload={true} downloadFilename="abetworks-time-tracking.md">
      <div className="table-responsive mb-3">
        <table className="table table-bordered">
          <thead className="table-light"><tr><th>Project</th><th>Hours</th><th>Rate ($/hr)</th><th>Earnings</th><th></th></tr></thead>
          <tbody>
            {projects.map((p, idx) => (
              <tr key={idx}>
                <td><input type="text" className="form-control" value={p.name} onChange={(e) => updateProject(idx, 'name', e.target.value)} /></td>
                <td><input type="number" className="form-control" value={p.hours} onChange={(e) => updateProject(idx, 'hours', parseFloat(e.target.value) || 0)} /></td>
                <td><input type="number" className="form-control" value={p.rate} onChange={(e) => updateProject(idx, 'rate', parseFloat(e.target.value) || 0)} /></td>
                <td>${(p.hours * p.rate).toFixed(2)}</td>
                <td><button className="btn btn-sm btn-outline-danger" onClick={() => removeProject(idx)} disabled={projects.length === 1}>×</button></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="d-flex gap-3"><button className="btn btn-outline-primary" onClick={addProject}>+ Add Project</button><button className="btn btn-primary btn-lg" onClick={calculate}>⏱️ Calculate</button></div>
      <div className="mt-4"><LeadCaptureForm toolName="Time Tracking Calculator" compact /></div>
    </ToolWrapper>
  );
};

// Expense Tracker
const ExpenseTracker: React.FC = () => {
  const [expenses, setExpenses] = useState([{ category: '', description: '', amount: 0, date: '' }]);
  const [result, setResult] = useState('');

  const addExpense = () => setExpenses([...expenses, { category: '', description: '', amount: 0, date: '' }]);
  const removeExpense = (idx: number) => expenses.length > 1 && setExpenses(expenses.filter((_, i) => i !== idx));
  const updateExpense = (idx: number, field: string, value: string | number) => {
    const updated = [...expenses];
    (updated[idx] as any)[field] = value;
    setExpenses(updated);
  };

  const calculate = () => {
    const total = expenses.reduce((sum, e) => sum + (e.amount || 0), 0);
    const byCategory: Record<string, number> = {};
    expenses.forEach(e => { byCategory[e.category || 'Uncategorized'] = (byCategory[e.category || 'Uncategorized'] || 0) + (e.amount || 0); });

    const output = `
# EXPENSE TRACKER SUMMARY

---

## EXPENSE LIST

| Date | Category | Description | Amount |
|------|----------|-------------|--------|
${expenses.map(e => `| ${e.date || '-'} | ${e.category || 'Uncategorized'} | ${e.description || '-'} | $${(e.amount || 0).toFixed(2)} |`).join('\n')}

---

## TOTALS

| Category | Amount |
|----------|--------|
${Object.entries(byCategory).map(([cat, amt]) => `| ${cat} | $${amt.toFixed(2)} |`).join('\n')}
| **TOTAL** | **$${total.toFixed(2)}** |

---

*Generated by Abetworks Expense Tracker*
`.trim();
    setResult(output);
  };

  return (
    <ToolWrapper title="Expense Tracker" description="Track and categorize your business expenses" icon="💸" inputValue="" outputValue={result} outputLabel="Expense Summary" showCopy={true} showDownload={true} downloadFilename="abetworks-expense-tracker.md">
      <div className="table-responsive mb-3">
        <table className="table table-bordered">
          <thead className="table-light"><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th></th></tr></thead>
          <tbody>
            {expenses.map((e, idx) => (
              <tr key={idx}>
                <td><input type="date" className="form-control" value={e.date} onChange={(e) => updateExpense(idx, 'date', e.target.value)} /></td>
                <td><input type="text" className="form-control" value={e.category} onChange={(e) => updateExpense(idx, 'category', e.target.value)} placeholder="e.g., Software" /></td>
                <td><input type="text" className="form-control" value={e.description} onChange={(e) => updateExpense(idx, 'description', e.target.value)} /></td>
                <td><input type="number" className="form-control" value={e.amount} onChange={(e) => updateExpense(idx, 'amount', parseFloat(e.target.value) || 0)} /></td>
                <td><button className="btn btn-sm btn-outline-danger" onClick={() => removeExpense(idx)} disabled={expenses.length === 1}>×</button></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="d-flex gap-3"><button className="btn btn-outline-primary" onClick={addExpense}>+ Add Expense</button><button className="btn btn-primary btn-lg" onClick={calculate}>💸 Calculate Total</button></div>
      <div className="mt-4"><LeadCaptureForm toolName="Expense Tracker" compact /></div>
    </ToolWrapper>
  );
};

// Tax Estimator
const TaxEstimator: React.FC = () => {
  const [inputs, setInputs] = useState({ income: 100000, expenses: 20000, filingStatus: 'single' });
  const [result, setResult] = useState('');

  const calculate = () => {
    const taxableIncome = inputs.income - inputs.expenses;
    const selfEmploymentTax = taxableIncome * 0.153;
    // Simplified tax brackets
    const brackets = inputs.filingStatus === 'single' 
      ? [{ max: 11000, rate: 0.1 }, { max: 44725, rate: 0.12 }, { max: 95375, rate: 0.22 }, { max: 182100, rate: 0.24 }, { max: Infinity, rate: 0.32 }]
      : [{ max: 22000, rate: 0.1 }, { max: 89450, rate: 0.12 }, { max: 190750, rate: 0.22 }, { max: 364200, rate: 0.24 }, { max: Infinity, rate: 0.32 }];
    
    let incomeTax = 0, prevMax = 0;
    for (const bracket of brackets) {
      if (taxableIncome > prevMax) {
        incomeTax += (Math.min(taxableIncome, bracket.max) - prevMax) * bracket.rate;
        prevMax = bracket.max;
      }
    }
    const totalTax = selfEmploymentTax + incomeTax;
    const effectiveRate = (totalTax / inputs.income) * 100;

    const output = `
# FREELANCE TAX ESTIMATOR

---

## INPUTS

| Metric | Value |
|--------|-------|
| Gross Income | $${inputs.income.toLocaleString()} |
| Business Expenses | $${inputs.expenses.toLocaleString()} |
| **Taxable Income** | **$${taxableIncome.toLocaleString()}** |
| Filing Status | ${inputs.filingStatus} |

---

## TAX BREAKDOWN

| Tax Type | Amount |
|----------|--------|
| Self-Employment Tax (15.3%) | $${selfEmploymentTax.toLocaleString()} |
| Federal Income Tax | $${incomeTax.toLocaleString()} |
| **Total Estimated Tax** | **$${totalTax.toLocaleString()}** |

---

## SUMMARY

| Metric | Value |
|--------|-------|
| Effective Tax Rate | ${effectiveRate.toFixed(1)}% |
| Quarterly Estimated Payment | $${(totalTax / 4).toLocaleString()} |
| Monthly to Set Aside | $${(totalTax / 12).toLocaleString()} |

---

*Generated by Abetworks Tax Estimator*
`.trim();
    setResult(output);
  };

  return (
    <ToolWrapper title="Freelance Tax Estimator" description="Estimate your self-employment and income taxes" icon="📊" inputValue="" outputValue={result} outputLabel="Tax Estimate" showCopy={true} showDownload={true} downloadFilename="abetworks-tax-estimate.md">
      <div className="row g-3">
        <div className="col-md-4"><label className="form-label">Gross Income ($)</label><input type="number" className="form-control" value={inputs.income} onChange={(e) => setInputs({ ...inputs, income: parseInt(e.target.value) || 0 })} /></div>
        <div className="col-md-4"><label className="form-label">Business Expenses ($)</label><input type="number" className="form-control" value={inputs.expenses} onChange={(e) => setInputs({ ...inputs, expenses: parseInt(e.target.value) || 0 })} /></div>
        <div className="col-md-4"><label className="form-label">Filing Status</label><select className="form-select" value={inputs.filingStatus} onChange={(e) => setInputs({ ...inputs, filingStatus: e.target.value })}><option value="single">Single</option><option value="married">Married Filing Jointly</option></select></div>
      </div>
      <div className="d-flex gap-3 mt-4"><button className="btn btn-primary btn-lg" onClick={calculate}>📊 Calculate Tax</button></div>
      <div className="mt-4"><LeadCaptureForm toolName="Tax Estimator" compact /></div>
    </ToolWrapper>
  );
};

export default TimeTrackingCalculator;
export { ExpenseTracker, TaxEstimator };
