import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

const InvoiceGenerator: React.FC = () => {
  const [invoice, setInvoice] = useState({
    fromName: '', fromEmail: '', fromAddress: '',
    toName: '', toEmail: '', toAddress: '',
    invoiceNumber: 'INV-001', date: new Date().toISOString().split('T')[0], dueDate: '',
    items: [{ description: '', quantity: 1, rate: 0 }],
    notes: '', taxRate: 0
  });
  const [output, setOutput] = useState('');

  const addItem = () => setInvoice({ ...invoice, items: [...invoice.items, { description: '', quantity: 1, rate: 0 }] });
  const removeItem = (idx: number) => invoice.items.length > 1 && setInvoice({ ...invoice, items: invoice.items.filter((_, i) => i !== idx) });
  const updateItem = (idx: number, field: string, value: string | number) => {
    const updated = [...invoice.items];
    (updated[idx] as any)[field] = value;
    setInvoice({ ...invoice, items: updated });
  };

  const generate = () => {
    const subtotal = invoice.items.reduce((sum, item) => sum + (item.quantity * item.rate), 0);
    const tax = subtotal * (invoice.taxRate / 100);
    const total = subtotal + tax;

    const output = `
# INVOICE
## ${invoice.fromName || 'Your Business'}

---

**Invoice Number:** ${invoice.invoiceNumber}
**Date:** ${invoice.date}
**Due Date:** ${invoice.dueDate || 'Upon Receipt'}

---

## FROM:
${invoice.fromName || '[Your Name]'}
${invoice.fromEmail || '[Your Email]'}
${invoice.fromAddress || '[Your Address]'}

## TO:
${invoice.toName || '[Client Name]'}
${invoice.toEmail || '[Client Email]'}
${invoice.toAddress || '[Client Address]'}

---

## ITEMS

| Description | Quantity | Rate | Amount |
|-------------|----------|------|--------|
${invoice.items.map(item => `| ${item.description || 'Service'} | ${item.quantity} | $${item.rate.toFixed(2)} | $${(item.quantity * item.rate).toFixed(2)} |`).join('\n')}

---

## SUMMARY

| | Amount |
|---|--------|
| Subtotal | $${subtotal.toFixed(2)} |
| Tax (${invoice.taxRate}%) | $${tax.toFixed(2)} |
| **Total Due** | **$${total.toFixed(2)}** |

---

## NOTES
${invoice.notes || 'Thank you for your business!'}

---

## PAYMENT TERMS
- Payment is due within the specified timeframe
- Please include invoice number with payment
- Late payments may incur additional fees

---

*Generated by Abetworks Invoice Generator*
`.trim();

    setOutput(output);
  };

  const downloadPDF = async () => {
    const template = document.getElementById('invoice-template');
    if (!template) return;
    
    template.style.display = 'block';
    
    try {
      const canvas = await html2canvas(template, { scale: 2 });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      const safeNumber = invoice.invoiceNumber.replace(/[^a-z0-9]/gi, '-');
      pdf.save(`abetworks-invoice-${safeNumber}.pdf`);
    } finally {
      template.style.display = 'none';
    }
  };

  const downloadWord = () => {
    const template = document.getElementById('invoice-template');
    if (!template) return;
    
    const header = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>Export HTML to Word</title></head><body>";
    const footer = "</body></html>";
    const sourceHTML = header + template.innerHTML + footer;
    
    const source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(sourceHTML);
    const fileDownload = document.createElement("a");
    document.body.appendChild(fileDownload);
    fileDownload.href = source;
    const safeNumber = invoice.invoiceNumber.replace(/[^a-z0-9]/gi, '-');
    fileDownload.download = `abetworks-invoice-${safeNumber}.doc`;
    fileDownload.click();
    document.body.removeChild(fileDownload);
  };

  return (
    <ToolWrapper
      title="Professional Invoice Generator"
      description="Create professional invoices for your freelance work"
      icon="📄"
      inputValue={invoice.fromName}
      outputValue={output}
      outputLabel="Invoice"
      showCopy={true}
      showDownload={true}
      downloadFilename={`abetworks-invoice-${invoice.invoiceNumber}.md`}
    >
      <div className="row g-3 mb-4">
        <div className="col-md-6">
          <h6 className="mb-2">From (Your Details)</h6>
          <input type="text" className="form-control mb-2" placeholder="Your Name/Business" value={invoice.fromName} onChange={(e) => setInvoice({ ...invoice, fromName: e.target.value })} />
          <input type="email" className="form-control mb-2" placeholder="Your Email" value={invoice.fromEmail} onChange={(e) => setInvoice({ ...invoice, fromEmail: e.target.value })} />
          <input type="text" className="form-control" placeholder="Your Address" value={invoice.fromAddress} onChange={(e) => setInvoice({ ...invoice, fromAddress: e.target.value })} />
        </div>
        <div className="col-md-6">
          <h6 className="mb-2">To (Client Details)</h6>
          <input type="text" className="form-control mb-2" placeholder="Client Name" value={invoice.toName} onChange={(e) => setInvoice({ ...invoice, toName: e.target.value })} />
          <input type="email" className="form-control mb-2" placeholder="Client Email" value={invoice.toEmail} onChange={(e) => setInvoice({ ...invoice, toEmail: e.target.value })} />
          <input type="text" className="form-control" placeholder="Client Address" value={invoice.toAddress} onChange={(e) => setInvoice({ ...invoice, toAddress: e.target.value })} />
        </div>
      </div>

      <div className="row g-3 mb-4">
        <div className="col-md-4">
          <label className="form-label">Invoice Number</label>
          <input type="text" className="form-control" value={invoice.invoiceNumber} onChange={(e) => setInvoice({ ...invoice, invoiceNumber: e.target.value })} />
        </div>
        <div className="col-md-4">
          <label className="form-label">Invoice Date</label>
          <input type="date" className="form-control" value={invoice.date} onChange={(e) => setInvoice({ ...invoice, date: e.target.value })} />
        </div>
        <div className="col-md-4">
          <label className="form-label">Due Date</label>
          <input type="date" className="form-control" value={invoice.dueDate} onChange={(e) => setInvoice({ ...invoice, dueDate: e.target.value })} />
        </div>
      </div>

      <h6 className="mb-3">Line Items</h6>
      {invoice.items.map((item, idx) => (
        <div key={idx} className="row g-3 mb-2 align-items-end">
          <div className="col-md-5">
            <label className="form-label small">Description</label>
            <input type="text" className="form-control" value={item.description} onChange={(e) => updateItem(idx, 'description', e.target.value)} placeholder="Service or product" />
          </div>
          <div className="col-md-2">
            <label className="form-label small">Quantity</label>
            <input type="number" className="form-control" value={item.quantity} onChange={(e) => updateItem(idx, 'quantity', parseInt(e.target.value) || 0)} />
          </div>
          <div className="col-md-2">
            <label className="form-label small">Rate ($)</label>
            <input type="number" className="form-control" value={item.rate} onChange={(e) => updateItem(idx, 'rate', parseFloat(e.target.value) || 0)} />
          </div>
          <div className="col-md-2">
            <label className="form-label small">Amount</label>
            <div className="form-control-plaintext fw-bold">${(item.quantity * item.rate).toFixed(2)}</div>
          </div>
          <div className="col-md-1">
            <button className="btn btn-sm btn-outline-danger" onClick={() => removeItem(idx)} disabled={invoice.items.length === 1}>×</button>
          </div>
        </div>
      ))}

      <div className="d-flex gap-3 mb-4">
        <button className="btn btn-outline-primary" onClick={addItem}>+ Add Item</button>
        <div className="ms-auto">
          <label className="form-label small">Tax Rate (%)</label>
          <input type="number" className="form-control" value={invoice.taxRate} onChange={(e) => setInvoice({ ...invoice, taxRate: parseFloat(e.target.value) || 0 })} style={{ width: '100px' }} />
        </div>
      </div>

      <div className="mb-4">
        <label className="form-label">Notes (optional)</label>
        <textarea className="form-control" rows={2} value={invoice.notes} onChange={(e) => setInvoice({ ...invoice, notes: e.target.value })} placeholder="Payment terms, thank you message, etc." />
      </div>

      <div className="d-flex gap-3 flex-wrap">
        <button className="btn btn-outline-primary" onClick={generate}>📝 Generate Text Version</button>
        <button className="btn btn-danger" onClick={downloadPDF}>📄 Download PDF</button>
        <button className="btn btn-primary" onClick={downloadWord}>📝 Download Word</button>
      </div>

      {/* Hidden visual template for PDF/Word export */}
      <div id="invoice-template" style={{ display: 'none', padding: '40px', background: '#fff', color: '#000', fontFamily: 'Arial, sans-serif', width: '800px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '40px' }}>
          <div>
            <h1 style={{ color: '#2563eb', margin: '0 0 10px 0', fontSize: '32px' }}>INVOICE</h1>
            <p style={{ margin: '0', color: '#6b7280' }}>Invoice #: {invoice.invoiceNumber}</p>
            <p style={{ margin: '0', color: '#6b7280' }}>Date: {invoice.date}</p>
            <p style={{ margin: '0', color: '#6b7280' }}>Due Date: {invoice.dueDate}</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <h2 style={{ margin: '0 0 5px 0', fontSize: '20px' }}>{invoice.fromName || 'Your Business'}</h2>
            <p style={{ margin: '0' }}>{invoice.fromEmail}</p>
            <p style={{ margin: '0' }}>{invoice.fromAddress}</p>
          </div>
        </div>

        <div style={{ marginBottom: '40px' }}>
          <h3 style={{ margin: '0 0 10px 0', borderBottom: '2px solid #e5e7eb', paddingBottom: '5px', color: '#374151' }}>Bill To:</h3>
          <p style={{ margin: '0', fontWeight: 'bold' }}>{invoice.toName}</p>
          <p style={{ margin: '0' }}>{invoice.toEmail}</p>
          <p style={{ margin: '0' }}>{invoice.toAddress}</p>
        </div>

        <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '40px' }}>
          <thead>
            <tr style={{ backgroundColor: '#f3f4f6', borderBottom: '2px solid #e5e7eb' }}>
              <th style={{ padding: '12px', textAlign: 'left', color: '#374151' }}>Description</th>
              <th style={{ padding: '12px', textAlign: 'center', color: '#374151' }}>Qty</th>
              <th style={{ padding: '12px', textAlign: 'right', color: '#374151' }}>Rate</th>
              <th style={{ padding: '12px', textAlign: 'right', color: '#374151' }}>Amount</th>
            </tr>
          </thead>
          <tbody>
            {invoice.items.map((item, idx) => (
              <tr key={idx} style={{ borderBottom: '1px solid #e5e7eb' }}>
                <td style={{ padding: '12px', textAlign: 'left' }}>{item.description}</td>
                <td style={{ padding: '12px', textAlign: 'center' }}>{item.quantity}</td>
                <td style={{ padding: '12px', textAlign: 'right' }}>${item.rate.toFixed(2)}</td>
                <td style={{ padding: '12px', textAlign: 'right' }}>${(item.quantity * item.rate).toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div style={{ width: '100%', display: 'flex', justifyContent: 'flex-end', marginBottom: '40px' }}>
          <table style={{ width: '300px' }}>
            <tbody>
              <tr>
                <td style={{ padding: '8px', textAlign: 'right', fontWeight: 'bold', color: '#374151' }}>Subtotal:</td>
                <td style={{ padding: '8px', textAlign: 'right' }}>${invoice.items.reduce((s, i) => s + (i.quantity * i.rate), 0).toFixed(2)}</td>
              </tr>
              <tr>
                <td style={{ padding: '8px', textAlign: 'right', fontWeight: 'bold', color: '#374151' }}>Tax ({invoice.taxRate}%):</td>
                <td style={{ padding: '8px', textAlign: 'right' }}>${(invoice.items.reduce((s, i) => s + (i.quantity * i.rate), 0) * (invoice.taxRate / 100)).toFixed(2)}</td>
              </tr>
              <tr style={{ backgroundColor: '#f3f4f6', borderTop: '2px solid #2563eb' }}>
                <td style={{ padding: '12px', textAlign: 'right', fontWeight: 'bold', fontSize: '18px', color: '#111827' }}>Total Due:</td>
                <td style={{ padding: '12px', textAlign: 'right', fontWeight: 'bold', fontSize: '18px', color: '#2563eb' }}>
                  ${(invoice.items.reduce((s, i) => s + (i.quantity * i.rate), 0) * (1 + invoice.taxRate / 100)).toFixed(2)}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        {invoice.notes && (
          <div style={{ marginTop: '40px', padding: '20px', backgroundColor: '#f9fafb', borderRadius: '8px', borderLeft: '4px solid #2563eb' }}>
            <h4 style={{ margin: '0 0 10px 0', color: '#374151' }}>Notes:</h4>
            <p style={{ margin: '0', color: '#6b7280', whiteSpace: 'pre-wrap' }}>{invoice.notes}</p>
          </div>
        )}
      </div>

      <div className="mt-4"><LeadCaptureForm toolName="Invoice Generator" compact /></div>
    </ToolWrapper>
  );
};

export default InvoiceGenerator;
