import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const PortfolioBuilder: React.FC = () => {
  const [data, setData] = useState({ name: '', title: '', email: '', website: '', bio: '', skills: '', projects: '' });
  const [portfolio, setPortfolio] = useState('');

  const generate = () => {
    const skillList = data.skills.split(',').map(s => s.trim()).filter(s => s);
    const output = `
# PORTFOLIO WEBSITE CONTENT
## ${data.name || 'Your Name'}

---

## HERO SECTION

**Headline:** ${data.title || '[Your Professional Title]'}

**Subheadline:** Helping clients achieve [specific outcome] through [your expertise]

**CTA:** [Let's Work Together] [View My Work]

---

## ABOUT ME

${data.bio || `
I'm ${data.name || 'a professional'} with expertise in ${skillList.join(', ') || 'my field'}. 

With [X] years of experience, I've helped [number]+ clients achieve [specific results].

My approach combines [unique approach] with [methodology] to deliver exceptional results.
`}

### Core Skills
${skillList.map(s => `- ${s}`).join('\n')}

---

## SERVICES

### Service 1: [Service Name]
**Description:** What you offer
**Deliverables:** What clients receive
**Starting at:** $[Price]

### Service 2: [Service Name]
**Description:** What you offer
**Deliverables:** What clients receive
**Starting at:** $[Price]

### Service 3: [Service Name]
**Description:** What you offer
**Deliverables:** What clients receive
**Starting at:** $[Price]

---

## FEATURED PROJECTS

${data.projects || `
### Project 1
**Client:** [Client Name]
**Challenge:** [What problem they had]
**Solution:** [What you did]
**Results:** [Quantifiable outcome]

### Project 2
**Client:** [Client Name]
**Challenge:** [What problem they had]
**Solution:** [What you did]
**Results:** [Quantifiable outcome]

### Project 3
**Client:** [Client Name]
**Challenge:** [What problem they had]
**Solution:** [What you did]
**Results:** [Quantifiable outcome]
`}

---

## TESTIMONIALS

> "[Great testimonial about working with you]"
> — [Client Name], [Title] at [Company]

> "[Another positive testimonial]"
> — [Client Name], [Title] at [Company]

---

## CONTACT

**Email:** ${data.email || 'your@email.com'}
**Website:** ${data.website || 'yourwebsite.com'}
**LinkedIn:** [Your LinkedIn URL]
**Location:** [Your Location / Remote]

---

## CALL TO ACTION

Ready to work together?

[Schedule a Call] [Send Message] [Get a Quote]

---

*Generated by Abetworks Portfolio Builder*
`.trim();
    setPortfolio(output);
  };

  return (
    <ToolWrapper title="Portfolio Builder" description="Create compelling portfolio content to showcase your work" icon="📁" inputValue={data.name} outputValue={portfolio} outputLabel="Portfolio Content" showCopy={true} showDownload={true} downloadFilename="abetworks-portfolio-content.md">
      <div className="row g-3">
        <div className="col-md-6"><label className="form-label">Your Name</label><input type="text" className="form-control" value={data.name} onChange={(e) => setData({ ...data, name: e.target.value })} /></div>
        <div className="col-md-6"><label className="form-label">Professional Title</label><input type="text" className="form-control" value={data.title} onChange={(e) => setData({ ...data, title: e.target.value })} placeholder="e.g., Freelance Designer" /></div>
        <div className="col-md-6"><label className="form-label">Email</label><input type="email" className="form-control" value={data.email} onChange={(e) => setData({ ...data, email: e.target.value })} /></div>
        <div className="col-md-6"><label className="form-label">Website</label><input type="url" className="form-control" value={data.website} onChange={(e) => setData({ ...data, website: e.target.value })} /></div>
        <div className="col-12"><label className="form-label">Bio/About</label><textarea className="form-control" rows={3} value={data.bio} onChange={(e) => setData({ ...data, bio: e.target.value })} placeholder="Tell us about yourself..." /></div>
        <div className="col-12"><label className="form-label">Skills (comma-separated)</label><input type="text" className="form-control" value={data.skills} onChange={(e) => setData({ ...data, skills: e.target.value })} placeholder="Web Design, UI/UX, Branding" /></div>
        <div className="col-12"><label className="form-label">Project Descriptions</label><textarea className="form-control" rows={4} value={data.projects} onChange={(e) => setData({ ...data, projects: e.target.value })} placeholder="Describe your key projects..." /></div>
      </div>
      <div className="d-flex gap-3 mt-4"><button className="btn btn-primary btn-lg" onClick={generate}>📁 Generate Portfolio</button></div>
      <div className="mt-4"><LeadCaptureForm toolName="Portfolio Builder" compact /></div>
    </ToolWrapper>
  );
};

export default PortfolioBuilder;
