import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

const ProposalTemplateGenerator: React.FC = () => {
  const [data, setData] = useState({
    yourName: '', yourCompany: '', yourEmail: '',
    clientName: '', clientCompany: '',
    projectTitle: '', projectOverview: '', deliverables: '',
    timeline: '', investment: '', whyUs: ''
  });
  const [proposal, setProposal] = useState('');

  const generate = () => {
    const output = `
# PROJECT PROPOSAL
## ${data.projectTitle || 'Project Title'}

---

**Prepared for:** ${data.clientName || '[Client Name]'} at ${data.clientCompany || '[Company]'}
**Prepared by:** ${data.yourName || '[Your Name]'} from ${data.yourCompany || '[Your Company]'}
**Date:** ${new Date().toLocaleDateString()}

---

## EXECUTIVE SUMMARY

Thank you for the opportunity to submit this proposal for ${data.projectTitle || 'your project'}. After understanding your needs, I'm excited to present a solution that will ${data.projectOverview ? 'address your key objectives' : 'help achieve your goals'}.

---

## PROJECT OVERVIEW

${data.projectOverview || '[Detailed description of the project, client needs, and objectives]'}

### Goals & Objectives
- [ ] Goal 1: [Specific, measurable objective]
- [ ] Goal 2: [Specific, measurable objective]
- [ ] Goal 3: [Specific, measurable objective]

---

## SCOPE OF WORK

### Deliverables

${data.deliverables || `
1. **Deliverable 1:** [Description]
2. **Deliverable 2:** [Description]
3. **Deliverable 3:** [Description]
`}

### What's Included
- [ ] Initial consultation and discovery
- [ ] Research and strategy
- [ ] Design/Development
- [ ] Revisions (specify number)
- [ ] Final delivery
- [ ] Post-project support

---

## PROJECT TIMELINE

${data.timeline || `
| Phase | Duration | Description |
|-------|----------|-------------|
| Discovery | 1-2 weeks | Research and planning |
| Design | 2-3 weeks | Concept and iterations |
| Development | 3-4 weeks | Implementation |
| Review | 1 week | Testing and revisions |
| Launch | 1 week | Deployment and handoff |
`}

**Estimated Start Date:** [Date]
**Estimated Completion:** [Date]

---

## INVESTMENT

${data.investment || `
### Package Options

**Basic Package:** $[Amount]
- Core deliverables
- Standard timeline
- Email support

**Professional Package:** $[Amount]
- All Basic features
- Priority support
- Additional revisions

**Premium Package:** $[Amount]
- Everything in Professional
- Expedited timeline
- Ongoing support
`}

### Payment Terms
- [ ] 50% deposit to begin work
- [ ] 25% at midpoint
- [ ] 25% upon completion
- [ ] Net 15 payment terms

---

## WHY CHOOSE US

${data.whyUs || `
- **Experience:** [X] years in the industry
- **Expertise:** Specialized skills in [area]
- **Track Record:** [X]+ successful projects
- **Communication:** Regular updates and transparent process
- **Support:** Ongoing assistance after project completion
`}

### Relevant Experience
- **Project 1:** [Brief description and results]
- **Project 2:** [Brief description and results]
- **Project 3:** [Brief description and results]

---

## NEXT STEPS

1. **Review this proposal** - Take your time to read through
2. **Ask questions** - I'm here to clarify anything
3. **Sign agreement** - Once ready, we'll finalize the contract
4. **Pay deposit** - 50% to secure your spot
5. **Kickoff meeting** - Let's get started!

---

## TERMS & CONDITIONS

- Proposal valid for 30 days from date
- Scope changes may affect timeline and cost
- Client feedback required within 5 business days
- Ownership transfers upon final payment

---

## ACCEPTANCE

**Client Signature:** _________________________

**Date:** _________________________

**Freelancer Signature:** _________________________

**Date:** _________________________

---

*Generated by Abetworks Proposal Template Generator*
`.trim();

    setProposal(output);
  };

  const downloadPDF = async () => {
    const template = document.getElementById('proposal-template');
    if (!template) return;
    template.style.display = 'block';
    try {
      const canvas = await html2canvas(template, { scale: 2 });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      const safeClient = (data.clientName || 'client').replace(/[^a-z0-9]/gi, '-');
      pdf.save(`abetworks-proposal-${safeClient}.pdf`);
    } finally {
      template.style.display = 'none';
    }
  };

  const downloadWord = () => {
    const template = document.getElementById('proposal-template');
    if (!template) return;
    const header = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>Export HTML to Word</title></head><body>";
    const footer = "</body></html>";
    const sourceHTML = header + template.innerHTML + footer;
    const source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(sourceHTML);
    const fileDownload = document.createElement("a");
    document.body.appendChild(fileDownload);
    fileDownload.href = source;
    const safeClient = (data.clientName || 'client').replace(/[^a-z0-9]/gi, '-');
    fileDownload.download = `abetworks-proposal-${safeClient}.doc`;
    fileDownload.click();
    document.body.removeChild(fileDownload);
  };

  return (
    <ToolWrapper
      title="Client Proposal Template Generator"
      description="Create winning client proposals that convert"
      icon="📝"
      inputValue={data.projectTitle}
      outputValue={proposal}
      outputLabel="Proposal Template"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-client-proposal.md"
    >
      <div className="row g-3 mb-4">
        <div className="col-md-6">
          <h6 className="mb-2">Your Details</h6>
          <input type="text" className="form-control mb-2" placeholder="Your Name" value={data.yourName} onChange={(e) => setData({ ...data, yourName: e.target.value })} />
          <input type="text" className="form-control mb-2" placeholder="Your Company" value={data.yourCompany} onChange={(e) => setData({ ...data, yourCompany: e.target.value })} />
          <input type="email" className="form-control" placeholder="Your Email" value={data.yourEmail} onChange={(e) => setData({ ...data, yourEmail: e.target.value })} />
        </div>
        <div className="col-md-6">
          <h6 className="mb-2">Client Details</h6>
          <input type="text" className="form-control mb-2" placeholder="Client Name" value={data.clientName} onChange={(e) => setData({ ...data, clientName: e.target.value })} />
          <input type="text" className="form-control" placeholder="Client Company" value={data.clientCompany} onChange={(e) => setData({ ...data, clientCompany: e.target.value })} />
        </div>
      </div>

      <div className="row g-3 mb-4">
        <div className="col-12">
          <label className="form-label">Project Title *</label>
          <input type="text" className="form-control" value={data.projectTitle} onChange={(e) => setData({ ...data, projectTitle: e.target.value })} placeholder="e.g., Website Redesign Project" />
        </div>
        <div className="col-12">
          <label className="form-label">Project Overview *</label>
          <textarea className="form-control" rows={3} value={data.projectOverview} onChange={(e) => setData({ ...data, projectOverview: e.target.value })} placeholder="Describe the client's needs and project objectives..." />
        </div>
        <div className="col-12">
          <label className="form-label">Deliverables</label>
          <textarea className="form-control" rows={3} value={data.deliverables} onChange={(e) => setData({ ...data, deliverables: e.target.value })} placeholder="List what you'll deliver..." />
        </div>
        <div className="col-md-6">
          <label className="form-label">Timeline</label>
          <textarea className="form-control" rows={2} value={data.timeline} onChange={(e) => setData({ ...data, timeline: e.target.value })} placeholder="Project phases and duration..." />
        </div>
        <div className="col-md-6">
          <label className="form-label">Investment/Pricing</label>
          <textarea className="form-control" rows={2} value={data.investment} onChange={(e) => setData({ ...data, investment: e.target.value })} placeholder="Pricing packages or total cost..." />
        </div>
        <div className="col-12">
          <label className="form-label">Why Choose You?</label>
          <textarea className="form-control" rows={2} value={data.whyUs} onChange={(e) => setData({ ...data, whyUs: e.target.value })} placeholder="Your unique value proposition..." />
        </div>
      </div>

      <div className="d-flex gap-3 flex-wrap">
        <button className="btn btn-outline-primary" onClick={generate}>📝 Generate Text Version</button>
        <button className="btn btn-danger" onClick={downloadPDF}>📄 Download PDF</button>
        <button className="btn btn-primary" onClick={downloadWord}>📝 Download Word</button>
      </div>

      {/* Hidden visual template for PDF/Word export */}
      <div id="proposal-template" style={{ display: 'none', padding: '40px', background: '#fff', color: '#1f2937', fontFamily: 'Arial, sans-serif', width: '800px', lineHeight: '1.6' }}>
        <div style={{ textAlign: 'center', marginBottom: '50px', borderBottom: '2px solid #3b82f6', paddingBottom: '20px' }}>
          <h1 style={{ color: '#1e3a8a', fontSize: '36px', margin: '0 0 10px 0', textTransform: 'uppercase', letterSpacing: '2px' }}>Project Proposal</h1>
          <h2 style={{ color: '#3b82f6', fontSize: '24px', margin: '0' }}>{data.projectTitle || 'Project Title'}</h2>
        </div>

        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '40px', backgroundColor: '#f3f4f6', padding: '20px', borderRadius: '8px' }}>
          <div>
            <h3 style={{ margin: '0 0 10px 0', color: '#4b5563', fontSize: '14px', textTransform: 'uppercase' }}>Prepared For:</h3>
            <p style={{ margin: '0', fontWeight: 'bold', fontSize: '18px' }}>{data.clientName || 'Client Name'}</p>
            <p style={{ margin: '0' }}>{data.clientCompany}</p>
          </div>
          <div style={{ textAlign: 'right' }}>
            <h3 style={{ margin: '0 0 10px 0', color: '#4b5563', fontSize: '14px', textTransform: 'uppercase' }}>Prepared By:</h3>
            <p style={{ margin: '0', fontWeight: 'bold', fontSize: '18px' }}>{data.yourName || 'Your Name'}</p>
            <p style={{ margin: '0' }}>{data.yourCompany}</p>
            <p style={{ margin: '0' }}>{data.yourEmail}</p>
            <p style={{ margin: '5px 0 0 0', color: '#6b7280', fontSize: '14px' }}>Date: {new Date().toLocaleDateString()}</p>
          </div>
        </div>

        <div style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#1e3a8a', borderBottom: '1px solid #e5e7eb', paddingBottom: '5px' }}>Executive Summary</h2>
          <p>Thank you for the opportunity to submit this proposal for <strong>{data.projectTitle || 'your project'}</strong>. After understanding your needs, we are excited to present a solution that will help achieve your goals effectively and efficiently.</p>
        </div>

        <div style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#1e3a8a', borderBottom: '1px solid #e5e7eb', paddingBottom: '5px' }}>Project Overview</h2>
          <p style={{ whiteSpace: 'pre-wrap' }}>{data.projectOverview || 'Detailed description of the project, client needs, and objectives.'}</p>
        </div>

        <div style={{ marginBottom: '30px' }}>
          <h2 style={{ color: '#1e3a8a', borderBottom: '1px solid #e5e7eb', paddingBottom: '5px' }}>Scope of Work & Deliverables</h2>
          <p style={{ whiteSpace: 'pre-wrap' }}>{data.deliverables || '1. Deliverable One\n2. Deliverable Two\n3. Deliverable Three'}</p>
        </div>

        <div style={{ display: 'flex', gap: '20px', marginBottom: '30px' }}>
          <div style={{ flex: 1 }}>
            <h2 style={{ color: '#1e3a8a', borderBottom: '1px solid #e5e7eb', paddingBottom: '5px' }}>Timeline</h2>
            <p style={{ whiteSpace: 'pre-wrap' }}>{data.timeline || 'Estimated timeline for project phases.'}</p>
          </div>
          <div style={{ flex: 1 }}>
            <h2 style={{ color: '#1e3a8a', borderBottom: '1px solid #e5e7eb', paddingBottom: '5px' }}>Investment</h2>
            <p style={{ whiteSpace: 'pre-wrap' }}>{data.investment || 'Pricing and package options.'}</p>
          </div>
        </div>

        <div style={{ marginBottom: '40px', backgroundColor: '#eff6ff', padding: '20px', borderRadius: '8px', borderLeft: '4px solid #3b82f6' }}>
          <h2 style={{ color: '#1e3a8a', margin: '0 0 10px 0' }}>Why Choose Us?</h2>
          <p style={{ margin: '0', whiteSpace: 'pre-wrap' }}>{data.whyUs || 'Unique value proposition and specialized skills.'}</p>
        </div>
        
        <div style={{ textAlign: 'center', marginTop: '50px', paddingTop: '20px', borderTop: '1px solid #e5e7eb', color: '#6b7280', fontSize: '12px' }}>
          <p>This proposal is valid for 30 days from the date of submission.</p>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Proposal Template Generator" compact /></div>
    </ToolWrapper>
  );
};

export default ProposalTemplateGenerator;
