import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const RateCalculator: React.FC = () => {
  const [inputs, setInputs] = useState({
    desiredAnnual: 100000,
    workingWeeks: 48,
    hoursPerWeek: 40,
    billablePercent: 70,
    expenses: 20000,
    taxRate: 25
  });
  const [result, setResult] = useState('');

  const calculate = () => {
    const { desiredAnnual, workingWeeks, hoursPerWeek, billablePercent, expenses, taxRate } = inputs;
    
    const totalHours = workingWeeks * hoursPerWeek;
    const billableHours = totalHours * (billablePercent / 100);
    const preTaxNeeded = desiredAnnual + expenses;
    const hourlyRate = preTaxNeeded / billableHours;
    const grossNeeded = preTaxNeeded / (1 - taxRate / 100);
    const hourlyWithTax = grossNeeded / billableHours;
    
    const dayRate = hourlyWithTax * 8;
    const weekRate = dayRate * 5;
    const monthRate = (grossNeeded / 12);

    const output = `
# FREELANCE RATE CALCULATOR

---

## YOUR INPUTS

| Metric | Value |
|--------|-------|
| Desired Annual Income | $${desiredAnnual.toLocaleString()} |
| Annual Expenses | $${expenses.toLocaleString()} |
| Working Weeks/Year | ${workingWeeks} |
| Hours/Week | ${hoursPerWeek} |
| Billable Time | ${billablePercent}% |
| Tax Rate | ${taxRate}% |

---

## CALCULATED RATES

### Minimum Hourly Rate (Pre-Tax)
**$${hourlyRate.toFixed(2)}/hour**

This covers your income + expenses before taxes.

### Recommended Hourly Rate (With Tax)
**$${hourlyWithTax.toFixed(2)}/hour**

This accounts for self-employment taxes and business expenses.

---

## RATE BREAKDOWN

| Rate Type | Amount |
|-----------|--------|
| **Hourly Rate** | $${hourlyWithTax.toFixed(2)} |
| **Day Rate (8 hrs)** | $${dayRate.toLocaleString()} |
| **Week Rate (40 hrs)** | $${weekRate.toLocaleString()} |
| **Monthly Retainer** | $${monthRate.toLocaleString()} |

---

## TIME ANALYSIS

| Category | Hours |
|----------|-------|
| Total Available Hours | ${totalHours.toLocaleString()} |
| Billable Hours (${billablePercent}%) | ${billableHours.toLocaleString()} |
| Non-Billable Hours | ${(totalHours - billableHours).toLocaleString()} |

### Non-Billable Time Includes:
- Marketing & sales
- Administrative tasks
- Professional development
- Client communication
- Project management

---

## SCENARIO COMPARISON

| Billable % | Hourly Rate Needed |
|------------|-------------------|
| 50% | $${(preTaxNeeded / (totalHours * 0.5 / (1 - taxRate / 100))).toFixed(2)} |
| 60% | $${(preTaxNeeded / (totalHours * 0.6 / (1 - taxRate / 100))).toFixed(2)} |
| 70% | $${hourlyWithTax.toFixed(2)} |
| 80% | $${(preTaxNeeded / (totalHours * 0.8 / (1 - taxRate / 100))).toFixed(2)} |

---

## RECOMMENDATIONS

### To Increase Your Effective Rate:
1. **Raise billable percentage** - Automate admin tasks
2. **Increase rates** - Don't undervalue your expertise
3. **Reduce expenses** - Work from home, use free tools
4. **Work more weeks** - Consider ${workingWeeks + 4} weeks/year
5. **Productivity boost** - More billable hours per week

### Industry Benchmarks:
- **Junior Freelancer:** $50-75/hour
- **Mid-Level:** $75-150/hour
- **Senior/Expert:** $150-300+/hour

---

## QUICK COMPARISONS

| Project Type | Suggested Rate |
|--------------|---------------|
| Small project (< 10 hrs) | $${(hourlyWithTax * 1.2).toFixed(2)}/hr (premium) |
| Medium project (10-50 hrs) | $${hourlyWithTax.toFixed(2)}/hr |
| Large project (50+ hrs) | $${(hourlyWithTax * 0.9).toFixed(2)}/hr (discount) |
| Retainer (monthly) | $${(monthRate * 0.9).toFixed(0)}/month (10% discount) |

---

*Generated by Abetworks Freelance Rate Calculator*
`.trim();

    setResult(output);
  };

  return (
    <ToolWrapper
      title="Freelance Rate Calculator"
      description="Calculate your ideal freelance hourly rate based on income goals"
      icon="💵"
      inputValue={`$${inputs.desiredAnnual.toLocaleString()}/year`}
      outputValue={result}
      outputLabel="Rate Calculation"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-freelance-rate-calculation.md"
    >
      <div className="row g-3">
        <div className="col-md-6">
          <label className="form-label">Desired Annual Income ($) *</label>
          <input type="number" className="form-control" value={inputs.desiredAnnual} onChange={(e) => setInputs({ ...inputs, desiredAnnual: parseInt(e.target.value) || 0 })} />
        </div>
        <div className="col-md-6">
          <label className="form-label">Annual Business Expenses ($) *</label>
          <input type="number" className="form-control" value={inputs.expenses} onChange={(e) => setInputs({ ...inputs, expenses: parseInt(e.target.value) || 0 })} />
        </div>
        <div className="col-md-4">
          <label className="form-label">Working Weeks/Year</label>
          <input type="number" className="form-control" value={inputs.workingWeeks} onChange={(e) => setInputs({ ...inputs, workingWeeks: parseInt(e.target.value) || 0 })} />
        </div>
        <div className="col-md-4">
          <label className="form-label">Hours/Week</label>
          <input type="number" className="form-control" value={inputs.hoursPerWeek} onChange={(e) => setInputs({ ...inputs, hoursPerWeek: parseInt(e.target.value) || 0 })} />
        </div>
        <div className="col-md-4">
          <label className="form-label">Billable Time (%)</label>
          <input type="number" className="form-control" value={inputs.billablePercent} onChange={(e) => setInputs({ ...inputs, billablePercent: parseInt(e.target.value) || 0 })} />
        </div>
        <div className="col-md-6">
          <label className="form-label">Tax Rate (%)</label>
          <input type="number" className="form-control" value={inputs.taxRate} onChange={(e) => setInputs({ ...inputs, taxRate: parseFloat(e.target.value) || 0 })} />
        </div>
      </div>

      <div className="d-flex gap-3 mt-4">
        <button className="btn btn-primary btn-lg" onClick={calculate}>💵 Calculate Rate</button>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Rate Calculator" compact /></div>
    </ToolWrapper>
  );
};

export default RateCalculator;
