import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const TestimonialRequestGenerator: React.FC = () => {
  const [clientName, setClientName] = useState('');
  const [projectType, setProjectType] = useState('');
  const [tone, setTone] = useState('friendly');
  const [requests, setRequests] = useState('');

  const generate = () => {
    const client = clientName || '[Client Name]';
    const project = projectType || 'the project';
    
    const templates: Record<string, Array<{ subject: string; body: string }>> = {
      friendly: [
        {
          subject: `Loved working with you! 💙`,
          body: `Hi ${client},\n\nIt was such a pleasure working with you on ${project}! I'm thrilled with how everything turned out.\n\nIf you have a moment, I'd be incredibly grateful if you could share your experience in a quick testimonial. Your feedback helps me reach more amazing clients like you!\n\n[Link to testimonial form]\n\nThank you so much!\n\nBest,\n[Your Name]`
        },
        {
          subject: `Quick favor? ☺️`,
          body: `Hey ${client},\n\nHope you're doing great!\n\nI'm collecting feedback from recent projects, and I'd love to hear about your experience working together on ${project}.\n\nWould you mind sharing 2-3 sentences about what it was like to work with me? It would mean the world!\n\n[Link or reply to this email]\n\nThanks a million!\n\n[Your Name]`
        }
      ],
      professional: [
        {
          subject: `Request for Testimonial - ${project}`,
          body: `Dear ${client},\n\nI hope this message finds you well.\n\nFollowing the successful completion of ${project}, I would be grateful if you could provide a brief testimonial about your experience working with me.\n\nYour feedback is invaluable in helping me serve clients better and grow my business.\n\n[Link to testimonial form]\n\nThank you for your time and consideration.\n\nBest regards,\n[Your Name]`
        }
      ],
      casual: [
        {
          subject: `Hey ${client}! Quick question...`,
          body: `Hey ${client}!\n\nHope all is well!\n\nQuick ask - would you be open to sharing a few words about working together on ${project}?\n\nNo pressure at all, but if you're happy with the work, a testimonial would be awesome! 🙏\n\n[Link or just hit reply]\n\nCheers!\n[Your Name]`
        }
      ]
    };

    const selectedTemplates = templates[tone] || templates.friendly;

    const output = `
# TESTIMONIAL REQUEST TEMPLATES
## Client: ${client}
## Project: ${project}
## Tone: ${tone}

---

## EMAIL TEMPLATE 1

**Subject:** ${selectedTemplates[0].subject}

\`\`\`
${selectedTemplates[0].body}
\`\`\`

---

## EMAIL TEMPLATE 2

**Subject:** ${selectedTemplates[1]?.subject || 'Follow-up: Testimonial Request'}

\`\`\`
${selectedTemplates[1]?.body || 'See template above'}
\`\`\`

---

## FOLLOW-UP TEMPLATE (Send after 1 week if no response)

**Subject:** Following up on my testimonial request

\`\`\`
Hi ${client},

Just wanted to gently follow up on my testimonial request from last week.

I know you're busy, so no worries if you haven't had a chance yet! If you do get a moment, here's the link again:

[Link to testimonial form]

Thanks again for everything!

Best,
[Your Name]
\`\`\`

---

## TESTIMONIAL PROMPTS TO MAKE IT EASIER

Help your client by suggesting what to write:

1. **What was the main challenge you were facing before working with me?**
2. **What was your experience like working together?**
3. **What results have you seen since we completed the project?**
4. **Would you recommend me to others? Why?**

---

## WHERE TO COLLECT TESTIMONIALS

- **Google Business Profile** - Great for local SEO
- **LinkedIn Recommendations** - Professional credibility
- **Your Website** - Direct control over display
- **Industry Platforms** - Upwork, Fiverr, etc.
- **Video Testimonials** - Loom, Vimeo, YouTube

---

## BEST PRACTICES

✅ **Do:**
- Ask soon after project completion
- Make it easy (provide prompts)
- Offer to draft it for them
- Follow up once (politely)
- Say thank you!

❌ **Don't:**
- Wait months to ask
- Make it complicated
- Pressure or guilt them
- Forget to show appreciation

---

*Generated by Abetworks Testimonial Request Generator*
`.trim();

    setRequests(output);
  };

  return (
    <ToolWrapper title="Testimonial Request Generator" description="Create effective testimonial request emails that get responses" icon="⭐" inputValue={clientName} outputValue={requests} outputLabel="Request Templates" showCopy={true} showDownload={true} downloadFilename="abetworks-testimonial-requests.md">
      <div className="row g-3">
        <div className="col-md-6"><label className="form-label">Client Name</label><input type="text" className="form-control" value={clientName} onChange={(e) => setClientName(e.target.value)} /></div>
        <div className="col-md-6"><label className="form-label">Project Type</label><input type="text" className="form-control" value={projectType} onChange={(e) => setProjectType(e.target.value)} placeholder="e.g., Website redesign" /></div>
        <div className="col-md-6"><label className="form-label">Email Tone</label><select className="form-select" value={tone} onChange={(e) => setTone(e.target.value)}><option value="friendly">Friendly</option><option value="professional">Professional</option><option value="casual">Casual</option></select></div>
        <div className="col-12"><button className="btn btn-primary btn-lg" onClick={generate}>⭐ Generate Requests</button></div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Testimonial Request Generator" compact /></div>
    </ToolWrapper>
  );
};

export default TestimonialRequestGenerator;
