import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const BacklinkTracker: React.FC = () => {
  const [domain, setDomain] = useState('');
  const [backlinks, setBacklinks] = useState([
    { url: '', anchor: '', da: '', status: 'active' }
  ]);
  const [report, setReport] = useState('');

  const addBacklink = () => setBacklinks([...backlinks, { url: '', anchor: '', da: '', status: 'active' }]);
  const removeBacklink = (idx: number) => backlinks.length > 1 && setBacklinks(backlinks.filter((_, i) => i !== idx));
  const updateBacklink = (idx: number, field: string, value: string) => {
    const updated = [...backlinks];
    (updated[idx] as any)[field] = value;
    setBacklinks(updated);
  };

  const generateReport = () => {
    const siteDomain = domain || 'yoursite.com';
    const activeLinks = backlinks.filter(b => b.status === 'active' && b.url);
    const lostLinks = backlinks.filter(b => b.status === 'lost');
    const avgDA = activeLinks.length > 0 
      ? Math.round(activeLinks.reduce((sum, b) => sum + (parseInt(b.da) || 0), 0) / activeLinks.length)
      : 0;

    const output = `
# BACKLINK TRACKING REPORT
## Domain: ${siteDomain}

---

## SUMMARY

| Metric | Value |
|--------|-------|
| Total Backlinks Tracked | ${backlinks.filter(b => b.url).length} |
| Active Backlinks | ${activeLinks.length} |
| Lost Backlinks | ${lostLinks.length} |
| Average Domain Authority | ${avgDA} |

---

## BACKLINK INVENTORY

| # | Source URL | Anchor Text | DA | Status |
|---|------------|-------------|-----|--------|
${backlinks.map((b, i) => `| ${i + 1} | ${b.url || '[URL]'} | ${b.anchor || '[Anchor]'} | ${b.da || '-'} | ${b.status === 'active' ? '✅' : '❌'} |`).join('\n')}

---

## BACKLINK ANALYSIS

### By Domain Authority
- **High Authority (DA 50+):** ${activeLinks.filter(b => parseInt(b.da) >= 50).length}
- **Medium Authority (DA 25-49):** ${activeLinks.filter(b => parseInt(b.da) >= 25 && parseInt(b.da) < 50).length}
- **Low Authority (DA <25):** ${activeLinks.filter(b => parseInt(b.da) < 25).length}

### By Anchor Text Type
- **Branded:** ${backlinks.filter(b => b.anchor.toLowerCase().includes(siteDomain.split('.')[0].toLowerCase())).length}
- **Exact Match:** ${backlinks.filter(b => b.anchor.length < 20 && !b.anchor.toLowerCase().includes('http')).length}
- **Generic:** ${backlinks.filter(b => ['click here', 'read more', 'learn more'].some(g => b.anchor.toLowerCase().includes(g))).length}
- **URL/Naked:** ${backlinks.filter(b => b.anchor.includes('http')).length}

---

## ACTION ITEMS

### Link Building Opportunities
1. Identify competitors' backlinks
2. Reach out for guest posting
3. Create linkable assets
4. Fix broken backlinks
5. Reclaim lost links

### Link Quality Improvement
${lostLinks.length > 0 ? `- **Priority:** Reclaim ${lostLinks.length} lost backlinks` : '- Maintain current backlink profile'}
- Focus on high-DA websites
- Diversify anchor text
- Remove toxic backlinks

### Monitoring Tasks
- [ ] Check for new backlinks weekly
- [ ] Monitor lost backlinks
- [ ] Track ranking changes
- [ ] Review anchor text distribution
- [ ] Disavow toxic links

---

## BACKLINK BUILDING STRATEGY

### Quick Wins (1-30 days)
- Claim unlinked brand mentions
- Fix broken backlinks
- Reach out to existing contacts
- Submit to relevant directories

### Medium Term (1-3 months)
- Guest posting campaign
- Create shareable infographics
- Build resource page links
- HARO (Help a Reporter Out) responses

### Long Term (3+ months)
- Develop linkable content assets
- Build industry relationships
- Create original research/data
- Establish thought leadership

---

## TOOLS FOR BACKLINK TRACKING

- **Free:** Google Search Console, Ubersuggest
- **Paid:** Ahrefs, SEMrush, Moz Pro, Majestic
- **Monitoring:** Google Alerts, Mention

---

## RED FLAGS TO WATCH

❌ **Toxic Backlink Signs:**
- Links from spammy directories
- Links from unrelated niches
- Exact-match anchor text over-optimization
- Links from penalized sites
- Sudden spike in low-quality links

**Action:** Use Google's Disavow Tool if you detect toxic links.

---

*Generated by Abetworks Backlink Tracker*
`.trim();

    setReport(output);
  };

  return (
    <ToolWrapper
      title="Backlink Tracker & Manager"
      description="Track and manage your backlink profile with this comprehensive tool"
      icon="🔗"
      inputValue={domain}
      outputValue={report}
      outputLabel="Backlink Report"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-backlink-report.md"
    >
      <div className="row g-3">
        <div className="col-md-6">
          <label className="form-label">Your Domain</label>
          <input type="text" className="form-control" value={domain} onChange={(e) => setDomain(e.target.value)} placeholder="yoursite.com" />
        </div>
      </div>

      <h6 className="mt-4 mb-3">Backlink Inventory</h6>
      <div className="table-responsive">
        <table className="table table-bordered">
          <thead className="table-light">
            <tr>
              <th>Source URL</th>
              <th>Anchor Text</th>
              <th>DA</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {backlinks.map((link, idx) => (
              <tr key={idx}>
                <td><input type="url" className="form-control" value={link.url} onChange={(e) => updateBacklink(idx, 'url', e.target.value)} placeholder="https://..." /></td>
                <td><input type="text" className="form-control" value={link.anchor} onChange={(e) => updateBacklink(idx, 'anchor', e.target.value)} placeholder="Anchor text" /></td>
                <td><input type="number" className="form-control" value={link.da} onChange={(e) => updateBacklink(idx, 'da', e.target.value)} placeholder="0-100" style={{ maxWidth: '80px' }} /></td>
                <td>
                  <select className="form-select" value={link.status} onChange={(e) => updateBacklink(idx, 'status', e.target.value)}>
                    <option value="active">Active</option>
                    <option value="lost">Lost</option>
                    <option value="pending">Pending</option>
                  </select>
                </td>
                <td><button className="btn btn-sm btn-outline-danger" onClick={() => removeBacklink(idx)} disabled={backlinks.length === 1}>Remove</button></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="d-flex gap-3 mb-4">
        <button className="btn btn-outline-primary" onClick={addBacklink}>+ Add Backlink</button>
        <button className="btn btn-primary btn-lg" onClick={generateReport}>🔗 Generate Report</button>
      </div>

      <div className="mt-4"><LeadCaptureForm toolName="Backlink Tracker" compact /></div>
    </ToolWrapper>
  );
};

export default BacklinkTracker;
