import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const CanonicalTagGenerator: React.FC = () => {
  const [baseUrl, setBaseUrl] = useState('');
  const [variants, setVariants] = useState([{ url: '', params: '' }]);
  const [result, setResult] = useState('');

  const addVariant = () => setVariants([...variants, { url: '', params: '' }]);
  const removeVariant = (idx: number) => variants.length > 1 && setVariants(variants.filter((_, i) => i !== idx));
  const updateVariant = (idx: number, field: string, value: string) => {
    const updated = [...variants];
    (updated[idx] as any)[field] = value;
    setVariants(updated);
  };

  const generate = () => {
    if (!baseUrl.trim()) return;

    const canonical = baseUrl.split('?')[0];
    
    const output = `
# CANONICAL TAG GENERATOR
## Base URL: ${baseUrl}

---

## PRIMARY CANONICAL TAG

\`\`\`html
<link rel="canonical" href="${canonical}" />
\`\`\`

---

## IMPLEMENTATION EXAMPLES

### In HTML <head>
\`\`\`html
<!DOCTYPE html>
<html>
<head>
    <title>Your Page Title</title>
    <link rel="canonical" href="${canonical}" />
</head>
<body>
    <!-- Page content -->
</body>
</html>
\`\`\`

### HTTP Header (for non-HTML)
\`\`\`
Link: <${canonical}>; rel="canonical"
\`\`\`

---

## URL VARIANTS THAT SHOULD POINT TO THIS CANONICAL

${variants.map((v, i) => `### Variant ${i + 1}
**URL:** ${v.url || '[URL]'}
**Parameters:** ${v.params || '[params]'}
**Canonical:** \`${v.url ? v.url.split('?')[0] : canonical}\` should point to \`${canonical}\`

`).join('\n')}

---

## COMMON CANONICAL SCENARIOS

### 1. HTTP vs HTTPS
\`\`\`html
<!-- HTTP page should canonicalize to HTTPS -->
<link rel="canonical" href="https://example.com/page" />
\`\`\`

### 2. WWW vs Non-WWW
\`\`\`html
<!-- www should canonicalize to non-www -->
<link rel="canonical" href="https://example.com/page" />
\`\`\`

### 3. URL Parameters
\`\`\`html
<!-- With tracking params -->
https://example.com/page?utm_source=google
https://example.com/page?ref=facebook
<!-- Both should canonicalize to: -->
<link rel="canonical" href="https://example.com/page" />
\`\`\`

### 4. Pagination
\`\`\`html
<!-- Page 1 -->
<link rel="canonical" href="https://example.com/articles" />

<!-- Page 2 -->
<link rel="canonical" href="https://example.com/articles?page=2" />
\`\`\`

### 5. Mobile vs Desktop
\`\`\`html
<!-- Mobile page -->
<link rel="canonical" href="https://www.example.com/page" />

<!-- Desktop page -->
<link rel="alternate" media="only screen and (max-width: 640px)" href="https://m.example.com/page" />
\`\`\`

---

## BEST PRACTICES

✅ **Do:**
- Always use absolute URLs
- Include canonical on the canonical page itself (self-referential)
- Use only one canonical per page
- Ensure canonical page returns 200 status
- Match canonical with sitemap URLs

❌ **Don't:**
- Point multiple pages to the same canonical (unless truly duplicates)
- Canonicalize to a 404 page
- Use canonical instead of 301 redirects for moved content
- Mix http and https in canonicals
- Block canonical URLs in robots.txt

---

## TESTING CHECKLIST

- [ ] Canonical tag is in <head> section
- [ ] URL is absolute (includes protocol)
- [ ] Canonical page is accessible (200 OK)
- [ ] No conflicting canonical signals
- [ ] Consistent with sitemap
- [ ] Tested with Google Search Console

---

*Generated by Abetworks Canonical Tag Generator*
`.trim();

    setResult(output);
  };

  return (
    <ToolWrapper
      title="Canonical Tag Generator"
      description="Generate proper canonical tags to avoid duplicate content issues"
      icon="🔗"
      inputValue={baseUrl}
      outputValue={result}
      outputLabel="Canonical Tags"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-canonical-tags.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Base/Canonical URL *</label>
          <input
            type="url"
            className="form-control"
            value={baseUrl}
            onChange={(e) => setBaseUrl(e.target.value)}
            placeholder="https://example.com/page"
          />
        </div>
      </div>

      <h6 className="mt-4 mb-3">URL Variants (optional)</h6>
      {variants.map((v, idx) => (
        <div key={idx} className="row g-3 mb-2 align-items-end">
          <div className="col-md-5">
            <label className="form-label small">Variant URL</label>
            <input type="text" className="form-control" value={v.url} onChange={(e) => updateVariant(idx, 'url', e.target.value)} placeholder="https://example.com/page?..." />
          </div>
          <div className="col-md-5">
            <label className="form-label small">Notes</label>
            <input type="text" className="form-control" value={v.params} onChange={(e) => updateVariant(idx, 'params', e.target.value)} placeholder="e.g., UTM params" />
          </div>
          <div className="col-md-2">
            <button className="btn btn-outline-danger" onClick={() => removeVariant(idx)} disabled={variants.length === 1}>Remove</button>
          </div>
        </div>
      ))}
      
      <div className="d-flex gap-3 mt-4">
        <button className="btn btn-outline-primary" onClick={addVariant}>+ Add Variant</button>
        <button className="btn btn-primary btn-lg" onClick={generate}>🔗 Generate Tags</button>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Canonical Tag Generator" compact /></div>
    </ToolWrapper>
  );
};

export default CanonicalTagGenerator;
