import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const HreflangTagGenerator: React.FC = () => {
  const [baseUrl, setBaseUrl] = useState('');
  const [languages, setLanguages] = useState([
    { code: 'en', country: 'US', url: '' },
    { code: 'es', country: 'ES', url: '' },
    { code: 'fr', country: 'FR', url: '' }
  ]);
  const [result, setResult] = useState('');

  const addLanguage = () => setLanguages([...languages, { code: '', country: '', url: '' }]);
  const removeLanguage = (idx: number) => languages.length > 1 && setLanguages(languages.filter((_, i) => i !== idx));
  const updateLanguage = (idx: number, field: string, value: string) => {
    const updated = [...languages];
    (updated[idx] as any)[field] = value;
    setLanguages(updated);
  };

  const generate = () => {
    if (!baseUrl.trim()) return;

    const allTags = languages.filter(l => l.code).map(l => {
      const lang = l.country ? `${l.code}-${l.country}` : l.code;
      const url = l.url || `${baseUrl}${l.code === 'en' && l.country === 'US' ? '' : '/' + l.code}`;
      return `<link rel="alternate" hreflang="${lang}" href="${url}" />`;
    });

    // Add x-default
    allTags.push(`<link rel="alternate" hreflang="x-default" href="${baseUrl}" />`);

    const output = `
# HREFLANG TAG GENERATOR
## Base URL: ${baseUrl}

---

## HTML IMPLEMENTATION

Add these tags to the <head> section of ALL language versions:

\`\`\`html
${allTags.join('\n')}
\`\`\`

---

## XML SITEMAP IMPLEMENTATION

\`\`\`xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
  ${languages.filter(l => l.code).map(l => {
    const lang = l.country ? `${l.code}-${l.country}` : l.code;
    const url = l.url || `${baseUrl}${l.code === 'en' && l.country === 'US' ? '' : '/' + l.code}`;
    return `
  <url>
    <loc>${url}</loc>
    ${languages.filter(l2 => l2.code).map(l2 => {
      const lang2 = l2.country ? `${l2.code}-${l2.country}` : l2.code;
      const url2 = l2.url || `${baseUrl}${l2.code === 'en' && l2.country === 'US' ? '' : '/' + l2.code}`;
      return `<xhtml:link rel="alternate" hreflang="${lang2}" href="${url2}" />`;
    }).join('\n    ')}
  </url>`;
  }).join('\n')}
</urlset>
\`\`\`

---

## HTTP HEADER IMPLEMENTATION (for PDFs, etc.)

\`\`\`
Link: ${allTags.map(t => {
  const match = t.match(/hreflang="([^"]+)" href="([^"]+)"/);
  return match ? `<${match[2]}>; rel="alternate"; hreflang="${match[1]}"` : '';
}).join(', ')}
\`\`\`

---

## LANGUAGE/REGION CONFIGURATIONS

| Language | Code | Tag | URL |
|----------|------|-----|-----|
${languages.filter(l => l.code).map(l => `| ${l.code.toUpperCase()}${l.country ? ` (${l.country})` : ''} | ${l.code}${l.country ? `-${l.country}` : ''} | ${l.code}${l.country ? `-${l.country}` : ''} | ${l.url || baseUrl} |`).join('\n')}
| Default | x-default | x-default | ${baseUrl} |

---

## COMMON HREFLANG CODES

### Language Codes
- en = English
- es = Spanish
- fr = French
- de = German
- it = Italian
- pt = Portuguese
- nl = Dutch
- pl = Polish
- ru = Russian
- ja = Japanese
- zh = Chinese
- ko = Korean
- ar = Arabic

### Country Codes (for regional targeting)
- US = United States
- GB = United Kingdom
- ES = Spain
- MX = Mexico
- FR = France
- DE = Germany
- IT = Italy
- BR = Brazil
- AU = Australia
- CA = Canada

---

## BEST PRACTICES

✅ **Do:**
- Include self-referential hreflang on each page
- Use correct language-country combinations
- Include x-default for users without matching language
- Implement consistently across all pages
- Use absolute URLs

❌ **Don't:**
- Mix relative and absolute URLs
- Forget to include all language versions on each page
- Use hreflang for same-language content (use canonical instead)
- Block hreflang URLs in robots.txt
- Forget to update when adding new languages

---

## TESTING TOOLS

- [Google Search Console - International Targeting](https://search.google.com/search-console/international-targeting)
- [Sistrix Hreflang Validator](https://www.sistrix.com/hreflang-validator/)
- [Aleyda Solis Hreflang Generator](https://www.aleydasolis.com/english/hreflang-tags-generator/)

---

*Generated by Abetworks Hreflang Tag Generator*
`.trim();

    setResult(output);
  };

  return (
    <ToolWrapper
      title="Hreflang Tag Generator"
      description="Generate hreflang tags for international and multilingual SEO"
      icon="🌐"
      inputValue={baseUrl}
      outputValue={result}
      outputLabel="Hreflang Tags"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-hreflang-tags.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Base URL *</label>
          <input type="url" className="form-control" value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} placeholder="https://example.com" />
        </div>
      </div>

      <h6 className="mt-4 mb-3">Language/Region Versions</h6>
      {languages.map((lang, idx) => (
        <div key={idx} className="card border-0 shadow-sm mb-2">
          <div className="card-body py-2">
            <div className="row g-2 align-items-center">
              <div className="col-md-3">
                <label className="form-label small">Language Code</label>
                <input type="text" className="form-control form-control-sm" value={lang.code} onChange={(e) => updateLanguage(idx, 'code', e.target.value)} placeholder="en" />
              </div>
              <div className="col-md-2">
                <label className="form-label small">Country</label>
                <input type="text" className="form-control form-control-sm" value={lang.country} onChange={(e) => updateLanguage(idx, 'country', e.target.value)} placeholder="US" />
              </div>
              <div className="col-md-5">
                <label className="form-label small">URL</label>
                <input type="url" className="form-control form-control-sm" value={lang.url} onChange={(e) => updateLanguage(idx, 'url', e.target.value)} placeholder="https://..." />
              </div>
              <div className="col-md-2">
                <button className="btn btn-sm btn-outline-danger" onClick={() => removeLanguage(idx)} disabled={languages.length === 1}>Remove</button>
              </div>
            </div>
          </div>
        </div>
      ))}

      <div className="d-flex gap-3 mt-4">
        <button className="btn btn-outline-primary" onClick={addLanguage}>+ Add Language</button>
        <button className="btn btn-primary btn-lg" onClick={generate}>🌐 Generate Tags</button>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Hreflang Tag Generator" compact /></div>
    </ToolWrapper>
  );
};

export default HreflangTagGenerator;
