import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const KeywordDensityChecker: React.FC = () => {
  const [text, setText] = useState('');
  const [keyword, setKeyword] = useState('');
  const [result, setResult] = useState('');

  const analyze = () => {
    if (!text.trim() || !keyword.trim()) return;

    const textLower = text.toLowerCase();
    const keywordLower = keyword.toLowerCase();
    const words = textLower.match(/\b\w+\b/g) || [];
    const totalWords = words.length;
    
    // Count keyword occurrences
    const keywordCount = (textLower.match(new RegExp(keywordLower, 'g')) || []).length;
    const density = totalWords > 0 ? (keywordCount / totalWords) * 100 : 0;

    // Find all words and their frequency
    const wordFreq: Record<string, number> = {};
    words.forEach(word => {
      if (word.length > 3) { // Ignore short words
        wordFreq[word] = (wordFreq[word] || 0) + 1;
      }
    });

    const topWords = Object.entries(wordFreq)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 20);

    const output = `
# KEYWORD DENSITY ANALYSIS

---

## PRIMARY KEYWORD: "${keyword.toUpperCase()}"

| Metric | Value |
|--------|-------|
| Occurrences | ${keywordCount} |
| Total Words | ${totalWords} |
| **Density** | **${density.toFixed(2)}%** |

### Density Assessment
${density < 1 ? `⚠️ **Too Low** - Consider using "${keyword}" more naturally throughout the text.` : density <= 2.5 ? `✅ **Optimal** - Keyword density is in the recommended 1-2.5% range.` : `⚠️ **Too High** - Risk of keyword stuffing. Consider reducing usage.`}

---

## TOP KEYWORDS BY FREQUENCY

| Rank | Keyword | Count | Density |
|------|---------|-------|---------|
${topWords.map((w, i) => `| ${i + 1} | ${w[0]} | ${w[1]} | ${((w[1] / totalWords) * 100).toFixed(2)}% |`).join('\n')}

---

## SEO RECOMMENDATIONS

### Keyword Density Best Practices
- **Ideal Range:** 1-2.5% for primary keyword
- **Secondary Keywords:** 0.5-1% each
- **Avoid Stuffing:** Don't force keywords unnaturally

### Content Optimization Tips
1. Use synonyms and related terms (LSI keywords)
2. Include keyword in headings (H1, H2)
3. Add keyword in first 100 words
4. Use in meta title and description
5. Include in image alt text

### Readability Check
- **Word Count:** ${totalWords} words
- **Reading Level:** ${totalWords < 300 ? 'Short form' : totalWords < 1000 ? 'Medium form' : 'Long form'} content
- **Recommendation:** ${totalWords < 300 ? 'Consider expanding to 500+ words for better SEO' : 'Good length for SEO'}

---

*Generated by Abetworks Keyword Density Checker*
`.trim();

    setResult(output);
  };

  return (
    <ToolWrapper
      title="Keyword Density Checker"
      description="Analyze keyword density and optimize your content for SEO"
      icon="📊"
      inputValue={text.substring(0, 50)}
      outputValue={result}
      outputLabel="Analysis Results"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-keyword-density.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Target Keyword *</label>
          <input
            type="text"
            className="form-control"
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            placeholder="e.g., digital marketing"
          />
        </div>
        <div className="col-12">
          <label className="form-label">Content Text *</label>
          <textarea
            className="form-control"
            rows={10}
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Paste your content here to analyze keyword density..."
          />
          <small className="text-muted">Word count: {(text.match(/\b\w+\b/g) || []).length}</small>
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={analyze}>📊 Analyze Density</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Keyword Density Checker" compact /></div>
    </ToolWrapper>
  );
};

export default KeywordDensityChecker;
