import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const MetaTagAnalyzer: React.FC = () => {
  const [url, setUrl] = useState('');
  const [html, setHtml] = useState('');
  const [result, setResult] = useState('');

  const analyze = () => {
    const content = html || url;
    if (!content.trim()) return;

    // Extract meta tags from HTML
    const titleMatch = html.match(/<title[^>]*>([^<]*)<\/title>/i);
    const title = titleMatch ? titleMatch[1].trim() : 'Not found';
    const titleLength = title.length;

    const metaDescMatch = html.match(/<meta[^>]*name=["']description["'][^>]*content=["']([^"']*)["'][^>]*>/i) ||
                         html.match(/<meta[^>]*content=["']([^"']*)["'][^>]*name=["']description["'][^>]*>/i);
    const description = metaDescMatch ? (metaDescMatch[1] || metaDescMatch[2] || '').trim() : 'Not found';
    const descLength = description.length;

    const canonicalMatch = html.match(/<link[^>]*rel=["']canonical["'][^>]*href=["']([^"']*)["'][^>]*>/i);
    const canonical = canonicalMatch ? canonicalMatch[1] : 'Not found';

    const ogTitleMatch = html.match(/<meta[^>]*property=["']og:title["'][^>]*content=["']([^"']*)["'][^>]*>/i);
    const ogTitle = ogTitleMatch ? ogTitleMatch[1] : 'Not found';

    const ogDescMatch = html.match(/<meta[^>]*property=["']og:description["'][^>]*content=["']([^"']*)["'][^>]*>/i);
    const ogDesc = ogDescMatch ? ogDescMatch[1] : 'Not found';

    const ogImageMatch = html.match(/<meta[^>]*property=["']og:image["'][^>]*content=["']([^"']*)["'][^>]*>/i);
    const ogImage = ogImageMatch ? ogImageMatch[1] : 'Not found';

    const robotsMatch = html.match(/<meta[^>]*name=["']robots["'][^>]*content=["']([^"']*)["'][^>]*>/i);
    const robots = robotsMatch ? robotsMatch[1] : 'Not specified';

    const viewportMatch = html.match(/<meta[^>]*name=["']viewport["'][^>]*content=["']([^"']*)["'][^>]*>/i);
    const viewport = viewportMatch ? viewportMatch[1] : 'Not found';

    const output = `
# META TAG ANALYSIS REPORT

---

## TITLE TAG

**Content:** ${title}

**Length:** ${titleLength} characters

**Status:** ${titleLength >= 30 && titleLength <= 60 ? '✅ Good' : titleLength < 30 ? '⚠️ Too short (30-60 recommended)' : '⚠️ Too long (30-60 recommended)'}

---

## META DESCRIPTION

**Content:** ${description}

**Length:** ${descLength} characters

**Status:** ${descLength >= 120 && descLength <= 160 ? '✅ Good' : descLength < 120 ? '⚠️ Too short (120-160 recommended)' : '⚠️ Too long (120-160 recommended)'}

---

## OPEN GRAPH TAGS

| Tag | Status | Value |
|-----|--------|-------|
| og:title | ${ogTitle !== 'Not found' ? '✅' : '❌'} | ${ogTitle.substring(0, 50)}${ogTitle.length > 50 ? '...' : ''} |
| og:description | ${ogDesc !== 'Not found' ? '✅' : '❌'} | ${ogDesc.substring(0, 50)}${ogDesc.length > 50 ? '...' : ''} |
| og:image | ${ogImage !== 'Not found' ? '✅' : '❌'} | ${ogImage !== 'Not found' ? 'Present' : 'Missing'} |

---

## TECHNICAL SEO TAGS

| Tag | Status |
|-----|--------|
| Canonical URL | ${canonical !== 'Not found' ? '✅' : '❌ Missing'} |
| Robots Meta | ${robots !== 'Not specified' ? `✅ (${robots})` : '⚠️ Not specified'} |
| Viewport | ${viewport !== 'Not found' ? '✅' : '❌ Missing'} |

---

## RECOMMENDATIONS

${titleLength < 30 || titleLength > 60 ? `### Title Optimization
- Current: ${titleLength} characters
- Target: 30-60 characters
- Tip: Include primary keyword near the beginning
` : '### Title: ✅ Well optimized'}

${descLength < 120 || descLength > 160 ? `### Description Optimization
- Current: ${descLength} characters
- Target: 120-160 characters
- Tip: Include call-to-action and primary keyword
` : '### Description: ✅ Well optimized'}

${canonical === 'Not found' ? `### Canonical Tag
- Add canonical URL to prevent duplicate content issues
- Format: <link rel="canonical" href="https://example.com/page" />
` : '### Canonical: ✅ Present'}

${ogImage === 'Not found' ? `### Open Graph Image
- Add og:image for better social media sharing
- Recommended size: 1200x630 pixels
` : '### Open Graph Image: ✅ Present'}

---

*Generated by Abetworks Meta Tag Analyzer*
`.trim();

    setResult(output);
  };

  return (
    <ToolWrapper
      title="Meta Tag Analyzer"
      description="Analyze and optimize your meta tags for better SEO and social sharing"
      icon="🏷️"
      inputValue={url}
      outputValue={result}
      outputLabel="Analysis Report"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-meta-tag-analysis.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Page URL (optional)</label>
          <input
            type="url"
            className="form-control"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="https://example.com/page"
          />
        </div>
        <div className="col-12">
          <label className="form-label">Or paste HTML source code:</label>
          <textarea
            className="form-control"
            rows={10}
            value={html}
            onChange={(e) => setHtml(e.target.value)}
            placeholder="Paste your page's HTML source code here..."
          />
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={analyze}>🏷️ Analyze Meta Tags</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Meta Tag Analyzer" compact /></div>
    </ToolWrapper>
  );
};

export default MetaTagAnalyzer;
