import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const OpenGraphPreview: React.FC = () => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [image, setImage] = useState('');
  const [url, setUrl] = useState('');
  const [siteName, setSiteName] = useState('');
  const [preview, setPreview] = useState('');

  const generate = () => {
    const output = `
# OPEN GRAPH TAGS
## Social Media Preview Generator

---

## GENERATE TAGS

\`\`\`html
<!-- Open Graph / Facebook -->
<meta property="og:type" content="website" />
<meta property="og:url" content="${url || 'https://example.com/page'}" />
<meta property="og:title" content="${title || 'Your Page Title'}" />
<meta property="og:description" content="${description || 'Your page description'}" />
<meta property="og:image" content="${image || 'https://example.com/image.jpg'}" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:site_name" content="${siteName || 'Your Site Name'}" />
<meta property="og:locale" content="en_US" />

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:url" content="${url || 'https://example.com/page'}" />
<meta name="twitter:title" content="${title || 'Your Page Title'}" />
<meta name="twitter:description" content="${description || 'Your page description'}" />
<meta name="twitter:image" content="${image || 'https://example.com/image.jpg'}" />
\`\`\`

---

## FACEBOOK PREVIEW

\`\`\`
┌─────────────────────────────────────────┐
│ ${siteName || 'Your Site'}              │
├─────────────────────────────────────────┤
│                                         │
│  ${title || 'Your Page Title'}          │
│                                         │
│  ${description?.substring(0, 100) || 'Your page description will appear here...'}${description && description.length > 100 ? '...' : ''}│
│                                         │
│  ${url || 'https://example.com'}        │
│                                         │
└─────────────────────────────────────────┘
\`\`\`

---

## LINKEDIN PREVIEW

\`\`\`
┌─────────────────────────────────────────┐
│                                         │
│  ${title || 'Your Page Title'}          │
│                                         │
│  ${description?.substring(0, 150) || 'Your page description will appear here...'}${description && description.length > 150 ? '...' : ''}│
│                                         │
│  ${siteName || 'Your Site'}             │
│                                         │
└─────────────────────────────────────────┘
\`\`\`

---

## TWITTER PREVIEW (Summary Large Image)

\`\`\`
┌─────────────────────────────────────────┐
│                                         │
│  ${image ? '[Image Preview]' : '[Add og:image for preview]'}       │
│                                         │
│  ${title || 'Your Page Title'}          │
│  ${description?.substring(0, 100) || 'Your page description...'}${description && description.length > 100 ? '...' : ''}│
│                                         │
│  ${url || 'https://example.com'}        │
│                                         │
└─────────────────────────────────────────┘
\`\`\`

---

## RECOMMENDED IMAGE SIZES

| Platform | Size | Ratio |
|----------|------|-------|
| Facebook | 1200 x 630 px | 1.91:1 |
| Twitter (Large) | 1200 x 675 px | 16:9 |
| LinkedIn | 1200 x 627 px | 1.91:1 |
| Pinterest | 1000 x 1500 px | 2:3 |

---

## TESTING TOOLS

- [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/)
- [Twitter Card Validator](https://cards-dev.twitter.com/validator)
- [LinkedIn Post Inspector](https://www.linkedin.com/post-inspector/)
- [Pinterest Pin It Builder](https://developers.pinterest.com/tools/build-a-pin-it-button/)

---

## BEST PRACTICES

✅ **Do:**
- Use high-quality images (minimum 1200x630)
- Write compelling titles (under 60 chars)
- Include clear descriptions (150-160 chars)
- Use absolute URLs
- Test before publishing

❌ **Don't:**
- Use placeholder images
- Write vague descriptions
- Forget to set og:type
- Use relative image URLs
- Skip Twitter Card tags

---

*Generated by Abetworks Open Graph Preview*
`.trim();

    setPreview(output);
  };

  return (
    <ToolWrapper
      title="Open Graph Preview Generator"
      description="Preview and generate Open Graph tags for social media sharing"
      icon="📱"
      inputValue={title}
      outputValue={preview}
      outputLabel="OG Tags & Preview"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-open-graph-tags.md"
    >
      <div className="card border-0 shadow-sm mb-4" style={{ background: '#f0f2f5' }}>
        <div className="card-body">
          <div style={{ background: '#fff', borderRadius: '8px', overflow: 'hidden', maxWidth: '500px' }}>
            {image && <img src={image} alt="Preview" style={{ width: '100%', height: '260px', objectFit: 'cover' }} />}
            <div className="p-3">
              <div className="text-muted small mb-1">{siteName || 'Your Site'}</div>
              <h5 className="mb-2" style={{ color: '#1d2129', fontSize: '16px' }}>{title || 'Your Page Title'}</h5>
              <p className="text-muted mb-2" style={{ fontSize: '14px' }}>{description || 'Your page description will appear here...'}</p>
              <div className="text-muted small" style={{ fontSize: '12px' }}>{url || 'https://example.com'}</div>
            </div>
          </div>
        </div>
      </div>

      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Page Title *</label>
          <input type="text" className="form-control" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Your page title" />
        </div>
        <div className="col-12">
          <label className="form-label">Description *</label>
          <textarea className="form-control" rows={3} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Your page description" />
        </div>
        <div className="col-md-6">
          <label className="form-label">Image URL</label>
          <input type="url" className="form-control" value={image} onChange={(e) => setImage(e.target.value)} placeholder="https://example.com/image.jpg" />
        </div>
        <div className="col-md-6">
          <label className="form-label">Page URL</label>
          <input type="url" className="form-control" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://example.com/page" />
        </div>
        <div className="col-md-6">
          <label className="form-label">Site Name</label>
          <input type="text" className="form-control" value={siteName} onChange={(e) => setSiteName(e.target.value)} placeholder="Your Site Name" />
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>📱 Generate OG Tags</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Open Graph Preview" compact /></div>
    </ToolWrapper>
  );
};

export default OpenGraphPreview;
