import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const SERPSimulator: React.FC = () => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [url, setUrl] = useState('');
  const [preview, setPreview] = useState('');

  const generatePreview = () => {
    const titleLength = title.length;
    const descLength = description.length;
    
    const truncatedTitle = titleLength > 60 ? title.substring(0, 57) + '...' : title;
    const truncatedDesc = descLength > 160 ? description.substring(0, 157) + '...' : description;

    const output = `
# GOOGLE SERP PREVIEW

---

## DESKTOP PREVIEW

\`\`\`
🔍 ${url || 'https://example.com/page'}

### ${truncatedTitle || 'Your Page Title Will Appear Here'}

${truncatedDesc || 'Your meta description will appear here. Make sure to write a compelling description that includes your target keywords and encourages users to click.'}

${url || 'https://example.com/page'}
\`\`\`

---

## MOBILE PREVIEW

\`\`\`
### ${truncatedTitle || 'Your Page Title'}

${truncatedDesc || 'Your meta description preview for mobile search results. Keep it concise and compelling.'}

${url || 'https://example.com'}
\`\`\`

---

## SEO METRICS

| Element | Your Value | Recommended | Status |
|---------|------------|-------------|--------|
| Title Length | ${titleLength} chars | 30-60 chars | ${titleLength >= 30 && titleLength <= 60 ? '✅' : '⚠️'} |
| Description Length | ${descLength} chars | 120-160 chars | ${descLength >= 120 && descLength <= 160 ? '✅' : '⚠️'} |
| URL Length | ${url.length} chars | < 100 chars | ${url.length <= 100 ? '✅' : '⚠️'} |

---

## OPTIMIZATION TIPS

### Title Tag
${titleLength < 30 ? `- ⚠️ Too short. Add more descriptive keywords.` : titleLength > 60 ? `- ⚠️ Too long. It may get truncated in search results.` : `- ✅ Good length!`}
- Include primary keyword near the beginning
- Make it compelling and unique
- Consider adding brand name at the end

### Meta Description
${descLength < 120 ? `- ⚠️ Too short. Expand to include more details.` : descLength > 160 ? `- ⚠️ Too long. It may get truncated in search results.` : `- ✅ Good length!`}
- Include target keywords naturally
- Add a clear call-to-action
- Highlight unique value proposition
- Make each page's description unique

### URL Structure
- Keep URLs short and descriptive
- Use hyphens to separate words
- Include target keyword if possible
- Avoid unnecessary parameters

---

## RICH SNIPPET POTENTIAL

Consider adding structured data for:
- ⭐ Star ratings
- 📅 Event dates
- 💰 Product prices
- ❓ FAQ schema
- 📝 Article metadata
- 🏢 Organization info

---

*Generated by Abetworks SERP Simulator*
`.trim();

    setPreview(output);
  };

  return (
    <ToolWrapper
      title="Google SERP Simulator"
      description="Preview how your page will appear in Google search results"
      icon="🔍"
      inputValue={title}
      outputValue={preview}
      outputLabel="SERP Preview"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-serp-preview.md"
    >
      <div className="card border-0 shadow-sm mb-4" style={{ background: '#f8f9fa' }}>
        <div className="card-body">
          <h6 className="text-muted mb-3">LIVE PREVIEW</h6>
          <div className="mb-2" style={{ color: '#202124', fontSize: '14px' }}>{url || 'https://example.com/page'}</div>
          <h5 className="mb-2" style={{ color: '#1a0dab', fontSize: '20px', cursor: 'pointer' }}>
            {title || 'Your Page Title Will Appear Here'}
          </h5>
          <div style={{ color: '#4d5156', fontSize: '14px', lineHeight: '1.58' }}>
            {description || 'Your meta description will appear here. Make sure to write a compelling description...'}
          </div>
        </div>
      </div>

      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Page Title *</label>
          <input
            type="text"
            className="form-control"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Your page title"
          />
          <small className="text-muted">{title.length}/60 characters recommended</small>
        </div>
        <div className="col-12">
          <label className="form-label">Meta Description *</label>
          <textarea
            className="form-control"
            rows={3}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Your meta description"
          />
          <small className="text-muted">{description.length}/160 characters recommended</small>
        </div>
        <div className="col-12">
          <label className="form-label">Page URL</label>
          <input
            type="url"
            className="form-control"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="https://example.com/page"
          />
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generatePreview}>🔍 Generate Full Preview</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="SERP Simulator" compact /></div>
    </ToolWrapper>
  );
};

export default SERPSimulator;
