import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const TwitterCardPreview: React.FC = () => {
  const [card, setCard] = useState('summary_large_image');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [image, setImage] = useState('');
  const [site, setSite] = useState('');
  const [creator, setCreator] = useState('');
  const [preview, setPreview] = useState('');

  const generate = () => {
    const twitterCard = card === 'summary_large_image' 
      ? `<meta name="twitter:image:alt" content="${title || 'Image description'}" />` 
      : '';

    const previewBox = card === 'summary_large_image'
      ? `
┌─────────────────────────────────────────┐
│  ┌───────────────────────────────────┐
│  │                                   │
│  │       ${image ? 'Image Preview' : '[Image]'}           │
│  │                                   │
│  │                                   │
│  └───────────────────────────────────┘
│  ${title || 'Your Page Title'}
│  ${description?.substring(0, 80) || 'Your page description...'}${description && description.length > 80 ? '...' : ''}
│  ${site || '@yourhandle'}
└─────────────────────────────────────────┘`
      : `
┌─────────────────────────────────────────┐
│  ┌─────────┐  ${title || 'Your Page Title'}
│  │         │  ${description?.substring(0, 60) || 'Your page description...'}${description && description.length > 60 ? '...' : ''}
│  │  Image  │
│  │         │  ${site || '@yourhandle'}
│  └─────────┘
└─────────────────────────────────────────┘`;

    const output = `
# TWITTER CARD TAGS
## Card Type: ${card}

---

## GENERATE TAGS

\`\`\`html
<!-- Twitter Card -->
<meta name="twitter:card" content="${card}" />
<meta name="twitter:site" content="${site || '@yourhandle'}" />
<meta name="twitter:creator" content="${creator || '@yourhandle'}" />
<meta name="twitter:title" content="${title || 'Your Page Title'}" />
<meta name="twitter:description" content="${description || 'Your page description'}" />
<meta name="twitter:image" content="${image || 'https://example.com/image.jpg'}" />
${twitterCard}
\`\`\`

---

## TWITTER PREVIEW

\`\`\`
${previewBox}
\`\`\`

---

## CARD TYPES EXPLAINED

### 1. Summary Large Image (Recommended)
- Large image at top of card
- Best for: Blog posts, articles, featured content
- Image size: 1200 x 675 pixels (16:9 ratio)

### 2. Summary Card
- Small thumbnail image
- Best for: General content, profiles
- Image size: 120 x 120 pixels (1:1 ratio)

### 3. App Card
- For mobile app promotion
- Includes app store links
- Requires additional app-specific tags

### 4. Player Card
- For embedded video/audio
- Includes media player
- Requires additional player tags

---

## IMAGE REQUIREMENTS

| Card Type | Min Size | Max Size | Ratio |
|-----------|----------|----------|-------|
| Summary Large Image | 300 x 157 | 4096 x 4096 | 16:9 |
| Summary | 120 x 120 | 4096 x 4096 | 1:1 |
| App | 800 x 800 | 4096 x 4096 | 1:1 |
| Player | 720 x 720 | 4096 x 4096 | 1:1 |

---

## BEST PRACTICES

✅ **Do:**
- Use high-quality, relevant images
- Write compelling titles (under 70 chars)
- Keep descriptions concise (under 200 chars)
- Include @username for attribution
- Test with Twitter Card Validator

❌ **Don't:**
- Use generic stock photos
- Write clickbait titles
- Exceed character limits
- Forget to verify your domain
- Use images with too much text

---

## TESTING TOOLS

- [Twitter Card Validator](https://cards-dev.twitter.com/validator)
- [Twitter Developer Tools](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards)

---

*Generated by Abetworks Twitter Card Preview*
`.trim();

    setPreview(output);
  };

  return (
    <ToolWrapper
      title="Twitter Card Preview Generator"
      description="Preview and generate Twitter Card tags for better social sharing"
      icon="🐦"
      inputValue={title}
      outputValue={preview}
      outputLabel="Twitter Card Tags"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-twitter-card-tags.md"
    >
      <div className="card border-0 shadow-sm mb-4" style={{ background: '#f8f9fa' }}>
        <div className="card-body">
          <div style={{ background: '#fff', border: '1px solid #e1e8ed', borderRadius: '16px', overflow: 'hidden', maxWidth: '500px' }}>
            {card === 'summary_large_image' ? (
              <>
                {image ? <img src={image} alt="Preview" style={{ width: '100%', height: '280px', objectFit: 'cover' }} /> : <div style={{ width: '100%', height: '280px', background: '#657786', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff' }}>Image Preview</div>}
                <div className="p-3">
                  <h5 className="mb-2" style={{ color: '#14171a', fontSize: '18px' }}>{title || 'Your Page Title'}</h5>
                  <p className="text-muted mb-2" style={{ fontSize: '15px' }}>{description || 'Your page description...'}</p>
                  <div className="text-muted small" style={{ fontSize: '13px' }}>{site || '@yourhandle'}</div>
                </div>
              </>
            ) : (
              <div className="p-3 d-flex gap-3">
                {image ? <img src={image} alt="Preview" style={{ width: '120px', height: '120px', objectFit: 'cover', borderRadius: '8px' }} /> : <div style={{ width: '120px', height: '120px', background: '#657786', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '12px' }}>Image</div>}
                <div>
                  <h5 className="mb-2" style={{ color: '#14171a', fontSize: '16px' }}>{title || 'Your Page Title'}</h5>
                  <p className="text-muted mb-2" style={{ fontSize: '14px' }}>{description?.substring(0, 100) || 'Your page description...'}</p>
                  <div className="text-muted small" style={{ fontSize: '13px' }}>{site || '@yourhandle'}</div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      <div className="row g-3">
        <div className="col-md-6">
          <label className="form-label">Card Type</label>
          <select className="form-select" value={card} onChange={(e) => setCard(e.target.value)}>
            <option value="summary_large_image">Summary Large Image</option>
            <option value="summary">Summary Card</option>
          </select>
        </div>
        <div className="col-12">
          <label className="form-label">Title *</label>
          <input type="text" className="form-control" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Your page title" />
        </div>
        <div className="col-12">
          <label className="form-label">Description *</label>
          <textarea className="form-control" rows={2} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Your page description" />
        </div>
        <div className="col-md-6">
          <label className="form-label">Image URL</label>
          <input type="url" className="form-control" value={image} onChange={(e) => setImage(e.target.value)} placeholder="https://example.com/image.jpg" />
        </div>
        <div className="col-md-6">
          <label className="form-label">Twitter @Username</label>
          <input type="text" className="form-control" value={site} onChange={(e) => setSite(e.target.value)} placeholder="@yourhandle" />
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>🐦 Generate Twitter Card</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Twitter Card Preview" compact /></div>
    </ToolWrapper>
  );
};

export default TwitterCardPreview;
