import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const BlogTitleGenerator: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [style, setStyle] = useState('howto');
  const [titles, setTitles] = useState('');

  const generate = () => {
    if (!topic.trim()) return;

    const templates: Record<string, string[]> = {
      howto: [
        `How to ${topic}: A Complete Guide`,
        `How to ${topic} in 10 Easy Steps`,
        `How to ${topic} Like a Pro`,
        `How to ${topic} Without ${topic} Problems`,
        `How to ${topic}: The Ultimate Guide for Beginners`,
        `How Anyone Can ${topic}`,
        `How to Finally ${topic} Once and For All`,
        `How to ${topic} in Just 7 Days`,
        `How to ${topic}: Step-by-Step Tutorial`,
        `How to Master ${topic}`
      ],
      listicle: [
        `10 Best Ways to ${topic}`,
        `7 ${topic} Tips That Will Change Your Life`,
        `15 ${topic} Hacks You Need to Know`,
        `5 ${topic} Mistakes You're Probably Making`,
        `20 ${topic} Ideas That Will Blow Your Mind`,
        `12 ${topic} Tools Every Professional Uses`,
        `8 ${topic} Trends to Watch`,
        `25 ${topic} Resources You'll Love`,
        `9 ${topic} Secrets Experts Don't Tell You`,
        `30 ${topic} Examples for Inspiration`
      ],
      question: [
        `What Is ${topic}? Everything You Need to Know`,
        `Why ${topic} Is the Future`,
        `Is ${topic} Worth It? An Honest Review`,
        `What Happens When You ${topic}?`,
        `Can You Really ${topic}? We Tested It`,
        `Who Should Try ${topic}?`,
        `When Is the Right Time to ${topic}?`,
        `Where to Start with ${topic}`,
        `Which ${topic} Method Is Best?`,
        `Are You Making These ${topic} Mistakes?`
      ],
      comparison: [
        `${topic} vs Traditional Methods: Which Is Better?`,
        `The Best ${topic} Tools Compared`,
        `${topic}: Free vs Paid Options`,
        `Top 5 ${topic} Solutions Ranked`,
        `${topic} Showdown: Head-to-Head Comparison`,
        `We Tested 10 ${topic} Products - Here's the Winner`,
        `${topic} Alternatives You Should Consider`,
        `Budget vs Premium ${topic}: Is It Worth It?`,
        `${topic} Platform Comparison 2024`,
        `DIY vs Professional ${topic}: Pros and Cons`
      ],
      secret: [
        `The Secret to ${topic} Nobody Tells You`,
        `${topic}: Industry Secrets Revealed`,
        `What ${topic} Experts Don't Want You to Know`,
        `The Hidden Truth About ${topic}`,
        `Secret ${topic} Strategies of Successful People`,
        `Underground ${topic} Techniques`,
        `The ${topic} Hack That Changed Everything`,
        `Confessions of a ${topic} Expert`,
        `Little-Known ${topic} Facts That Matter`,
        `The Real Story Behind ${topic}`
      ]
    };

    const output = `
# BLOG TITLE IDEAS
## Topic: ${topic}
## Style: ${style}

---

### Generated Titles

${templates[style]?.map((t, i) => `${i + 1}. ${t}`).join('\n')}

---

## SEO TIPS FOR BLOG TITLES

✅ **Best Practices:**
- Include primary keyword near the beginning
- Keep under 60 characters for SERP display
- Use numbers for listicles (they perform well)
- Add power words: Ultimate, Complete, Best, Proven
- Create curiosity without clickbait

📊 **Title Performance:**
- Listicles: 36% higher CTR
- How-to: Evergreen, consistent traffic
- Questions: Match search intent
- Comparisons: High conversion intent

---

## TITLE FORMULA TEMPLATES

1. **How to [Achieve Result] Without [Pain Point]**
2. **[Number] [Adjective] Tips for [Specific Outcome]**
3. **The Ultimate Guide to [Topic] for [Audience]**
4. **[Topic] vs [Alternative]: Which Should You Choose?**
5. **What [Expert/Group] Can Teach Us About [Topic]**

---

*Generated by Abetworks Blog Title Generator*
`.trim();

    setTitles(output);
  };

  return (
    <ToolWrapper
      title="Blog Title Generator"
      description="Generate catchy, SEO-friendly blog post titles that drive clicks"
      icon="✍️"
      inputValue={topic}
      outputValue={titles}
      outputLabel="Blog Titles"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-blog-titles.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Blog Topic *</label>
          <input
            type="text"
            className="form-control"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g., weight loss, digital marketing, cooking"
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Title Style</label>
          <select className="form-select" value={style} onChange={(e) => setStyle(e.target.value)}>
            <option value="howto">How-To Guide</option>
            <option value="listicle">Listicle (List Post)</option>
            <option value="question">Question-Based</option>
            <option value="comparison">Comparison</option>
            <option value="secret">Secret/Revealed</option>
          </select>
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>✍️ Generate Titles</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Blog Title Generator" compact /></div>
    </ToolWrapper>
  );
};

export default BlogTitleGenerator;
