import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const BrandVoiceGenerator: React.FC = () => {
  const [companyName, setCompanyName] = useState('');
  const [values, setValues] = useState('');
  const [audience, setAudience] = useState('');
  const [voice, setVoice] = useState('');

  const generate = () => {
    const name = companyName || 'Company';
    const valueList = values.split(',').map(v => v.trim()).filter(v => v);
    const targetAudience = audience || 'target audience';

    const archetypes = [
      { name: 'The Hero', traits: 'Bold, inspiring, courageous', example: 'Nike - Just Do It' },
      { name: 'The Sage', traits: 'Wise, knowledgeable, trustworthy', example: 'Google - Organize information' },
      { name: 'The Jester', traits: 'Fun, playful, entertaining', example: 'Old Spice - Humorous ads' },
      { name: 'The Caregiver', traits: 'Nurturing, supportive, protective', example: 'Johnson & Johnson' },
      { name: 'The Creator', traits: 'Innovative, imaginative, artistic', example: 'Apple - Think Different' },
      { name: 'The Rebel', traits: 'Disruptive, bold, challenging', example: 'Harley-Davidson' }
    ];

    const output = `
# BRAND VOICE GUIDE
## ${name.toUpperCase()}

---

## BRAND FOUNDATIONS

### Core Values
${valueList.length > 0 ? valueList.map(v => `- ${v}`).join('\n') : '- [Define your core values]'}

### Target Audience
${targetAudience}

### Brand Personality
[Describe 3-5 personality traits, e.g., friendly, professional, innovative]

---

## BRAND ARCHETYPE

Based on your values, consider these archetypes:

${archetypes.map(a => `### ${a.name}
**Traits:** ${a.traits}
**Example:** ${a.example}

`).join('\n')}

---

## VOICE CHARACTERISTICS

### We Are:
- [Trait 1]: e.g., Friendly but professional
- [Trait 2]: e.g., Knowledgeable but accessible
- [Trait 3]: e.g., Confident but humble

### We Are Not:
- [Opposite 1]: e.g., Not casual or sloppy
- [Opposite 2]: e.g., Not condescending or arrogant
- [Opposite 3]: e.g., Not timid or uncertain

---

## TONE BY SITUATION

| Situation | Tone | Example |
|-----------|------|---------|
| Marketing Copy | [e.g., Enthusiastic] | "Transform your workflow today!" |
| Customer Support | [e.g., Empathetic] | "We understand your frustration..." |
| Error Messages | [e.g., Helpful] | "Something went wrong. Here's how to fix it." |
| Social Media | [e.g., Conversational] | "Hey friends! Check this out 👋" |
| Professional/Enterprise | [e.g., Authoritative] | "Industry-leading solution for..." |

---

## WRITING GUIDELINES

### Do:
- Use active voice
- Write in plain language
- Address the reader as "you"
- Keep sentences concise
- Show personality while staying professional

### Don't:
- Use jargon without explanation
- Write in passive voice
- Sound robotic or corporate
- Use excessive exclamation points!!!
- Make promises you can't keep

---

## WORD BANK

### Words We Use:
- Transform
- Empower
- Simplify
- Accelerate
- Trusted
- Innovative

### Words We Avoid:
- Leverage (use "use")
- Synergy (use "collaboration")
- Disrupt (use "improve")
- Best-in-class (show, don't tell)
- Cutting-edge (be specific)

---

## EXAMPLE MESSAGING

### Homepage Headline
**Before:** "We provide enterprise solutions for businesses"
**After:** "Transform your business with tools that work as hard as you do"

### Product Description
**Before:** "Our software features advanced algorithms"
**After:** "Get answers faster with smart technology that learns from you"

### Error Message
**Before:** "Error 404: Page not found"
**After:** "Oops! This page went on vacation. Let's get you back home."

### Social Media Post
**Before:** "New feature released. Read more."
**After:** "🎉 The feature you've been asking for is here! Tap to try it →"

---

## IMPLEMENTATION CHECKLIST

- [ ] Share this guide with all team members
- [ ] Create templates for common communications
- [ ] Review existing content for alignment
- [ ] Set up regular voice audits
- [ ] Train customer-facing teams
- [ ] Update style guide documentation

---

*Generated by Abetworks Brand Voice Generator*
`.trim();

    setVoice(output);
  };

  return (
    <ToolWrapper
      title="Brand Voice Generator"
      description="Define your brand's unique voice and create consistent messaging across all channels"
      icon="🎙️"
      inputValue={companyName}
      outputValue={voice}
      outputLabel="Brand Voice Guide"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-brand-voice-guide.md"
    >
      <div className="row g-3">
        <div className="col-md-6">
          <label className="form-label">Company/Brand Name *</label>
          <input type="text" className="form-control" value={companyName} onChange={(e) => setCompanyName(e.target.value)} />
        </div>
        <div className="col-md-6">
          <label className="form-label">Target Audience</label>
          <input type="text" className="form-control" value={audience} onChange={(e) => setAudience(e.target.value)} placeholder="e.g., Tech-savvy millennials" />
        </div>
        <div className="col-12">
          <label className="form-label">Core Values (comma-separated)</label>
          <input type="text" className="form-control" value={values} onChange={(e) => setValues(e.target.value)} placeholder="e.g., Innovation, Integrity, Customer-first" />
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>🎙️ Generate Brand Voice</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Brand Voice Generator" compact /></div>
    </ToolWrapper>
  );
};

export default BrandVoiceGenerator;
