import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const CallToActionGenerator: React.FC = () => {
  const [goal, setGoal] = useState('');
  const [urgency, setUrgency] = useState('medium');
  const [ctas, setCtas] = useState('');

  const generate = () => {
    if (!goal.trim()) return;

    const urgencyLevels: Record<string, string[]> = {
      low: ['Learn More', 'Get Started', 'Discover More', 'Explore Now', 'Find Out How'],
      medium: ['Start Free Trial', 'Get Your Free Guide', 'Claim Your Spot', 'Download Now', 'Join Today'],
      high: ['Limited Time - Act Now', 'Last Chance', 'Only 3 Spots Left', 'Sale Ends Tonight', 'Don\'t Miss Out']
    };

    const templates = [
      `Ready to ${goal}? [CTA]`,
      `Start ${goal} today - [CTA]`,
      `Join thousands who ${goal} - [CTA]`,
      `Your ${goal} journey starts here - [CTA]`,
      `Don't wait - ${goal} now - [CTA]`,
      `Transform your life - ${goal} - [CTA]`,
      `Take the first step - ${goal} - [CTA]`,
      `Get started with ${goal} - [CTA]`
    ];

    const ctas = urgencyLevels[urgency];
    
    const output = `
# CALL-TO-ACTION (CTA) IDEAS
## Goal: ${goal}
## Urgency: ${urgency}

---

## PRIMARY CTAS

${ctas.map((cta, i) => `${i + 1}. **${cta}**`).join('\n')}

---

## CTA VARIATIONS

${templates.map((t, i) => `${i + 1}. ${t.replace('[CTA]', ctas[i % ctas.length])}`).join('\n')}

---

## CTA BEST PRACTICES

✅ **Do:**
- Use action verbs
- Create urgency when appropriate
- Keep it short (2-5 words)
- Make it benefit-focused
- Test different colors and placements

❌ **Don't:**
- Use vague language
- Make it sound demanding
- Forget mobile optimization
- Use too many CTAs on one page
- Hide the CTA

---

## BUTTON COPY BY GOAL

**Sign Up:** Get Started Free, Create Account, Join Now
**Download:** Download Free, Get Your Copy, Instant Access
**Purchase:** Add to Cart, Buy Now, Shop Today
**Learn:** Learn More, See How, Discover More
**Contact:** Get in Touch, Contact Us, Talk to Sales

---

*Generated by Abetworks CTA Generator*
`.trim();

    setCtas(output);
  };

  return (
    <ToolWrapper
      title="Call-to-Action Generator"
      description="Create compelling CTAs that drive clicks and conversions"
      icon="🔘"
      inputValue={goal}
      outputValue={ctas}
      outputLabel="CTA Ideas"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-cta-ideas.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Desired Action/Goal *</label>
          <input type="text" className="form-control" value={goal} onChange={(e) => setGoal(e.target.value)} placeholder="e.g., start fitness journey, learn marketing" />
        </div>
        <div className="col-md-6">
          <label className="form-label">Urgency Level</label>
          <select className="form-select" value={urgency} onChange={(e) => setUrgency(e.target.value)}>
            <option value="low">Low (Evergreen)</option>
            <option value="medium">Medium (Standard)</option>
            <option value="high">High (Urgent)</option>
          </select>
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>🔘 Generate CTAs</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Call-to-Action Generator" compact /></div>
    </ToolWrapper>
  );
};

export default CallToActionGenerator;
