import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const ContentCalendarGenerator: React.FC = () => {
  const [niche, setNiche] = useState('');
  const [platforms, setPlatforms] = useState<string[]>(['instagram']);
  const [weeks, setWeeks] = useState(4);
  const [calendar, setCalendar] = useState('');

  const contentTypes: Record<string, string[]> = {
    instagram: ['Photo Post', 'Reel', 'Story', 'Carousel', 'IGTV'],
    twitter: ['Thread', 'Single Tweet', 'Poll', 'Quote Tweet', 'Video'],
    linkedin: ['Article', 'Post', 'Video', 'Poll', 'Document'],
    facebook: ['Photo', 'Video', 'Link Share', 'Live', 'Story'],
    tiktok: ['Dance', 'Tutorial', 'Trend', 'Duet', 'Story']
  };

  const contentIdeas = [
    'Behind the scenes',
    'Tips & tutorials',
    'User-generated content',
    'Product showcase',
    'Industry news',
    'Motivational quote',
    'FAQ answer',
    'Team spotlight',
    'Customer testimonial',
    'How-to guide',
    'Myth busting',
    'Trending topic',
    'Throwback post',
    'Poll/Question',
    'Live Q&A'
  ];

  const generate = () => {
    if (!niche.trim()) return;

    const selectedPlatforms = platforms.length > 0 ? platforms : ['instagram'];
    let output = `# CONTENT CALENDAR\n## Niche: ${niche}\n## Duration: ${weeks} weeks\n\n---\n\n`;

    for (let week = 1; week <= weeks; week++) {
      output += `## WEEK ${week}\n\n`;
      output += '| Day | Platform | Content Type | Topic/Idea | Status |\n';
      output += '|-----|----------|--------------|------------|--------|\n';
      
      const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
      days.forEach((day, idx) => {
        const platform = selectedPlatforms[idx % selectedPlatforms.length];
        const contentType = contentTypes[platform]?.[idx % contentTypes[platform].length] || 'Post';
        const idea = contentIdeas[(week * idx) % contentIdeas.length];
        output += `| ${day} | ${platform} | ${contentType} | ${idea} - ${niche} | 📝 Planned |\n`;
      });
      output += '\n---\n\n';
    }

    output += `
## CONTENT PILLARS FOR ${niche.toUpperCase()}

1. **Educational** - Tips, tutorials, how-tos
2. **Inspirational** - Success stories, quotes, motivation
3. **Entertainment** - Trends, humor, behind-the-scenes
4. **Promotional** - Products, services, offers

## POSTING SCHEDULE RECOMMENDATIONS

${selectedPlatforms.map(p => `- **${p}:** ${p === 'instagram' ? '1-2 posts/day' : p === 'twitter' ? '3-5 tweets/day' : p === 'linkedin' ? '1 post/day (weekdays)' : p === 'facebook' ? '1-2 posts/day' : '1-3 videos/day'}`).join('\n')}

## HASHTAG STRATEGY
- Use 5-10 niche-specific hashtags
- Include 3-5 trending hashtags
- Create 1-2 branded hashtags

---

*Generated by Abetworks Content Calendar Generator*
`.trim();

    setCalendar(output);
  };

  return (
    <ToolWrapper
      title="Content Calendar Generator"
      description="Plan your social media content with a ready-to-use content calendar"
      icon="📅"
      inputValue={niche}
      outputValue={calendar}
      outputLabel="Content Calendar"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-content-calendar.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Niche/Industry *</label>
          <input
            type="text"
            className="form-control"
            value={niche}
            onChange={(e) => setNiche(e.target.value)}
            placeholder="e.g., Fitness, Tech, Fashion"
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Platforms (select multiple)</label>
          <select className="form-select" multiple value={platforms} onChange={(e) => setPlatforms(Array.from(e.target.selectedOptions, option => option.value))}>
            <option value="instagram">Instagram</option>
            <option value="twitter">Twitter/X</option>
            <option value="linkedin">LinkedIn</option>
            <option value="facebook">Facebook</option>
            <option value="tiktok">TikTok</option>
          </select>
          <small className="text-muted">Hold Ctrl/Cmd to select multiple</small>
        </div>
        <div className="col-md-6">
          <label className="form-label">Number of Weeks</label>
          <input type="number" className="form-control" min="1" max="12" value={weeks} onChange={(e) => setWeeks(parseInt(e.target.value) || 4)} />
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>📅 Generate Calendar</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Content Calendar Generator" compact /></div>
    </ToolWrapper>
  );
};

export default ContentCalendarGenerator;
