import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const EmailSubjectLineGenerator: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [type, setType] = useState('promotional');
  const [subjects, setSubjects] = useState('');

  const generate = () => {
    if (!topic.trim()) return;

    const templates: Record<string, string[]> = {
      promotional: [
        `🎉 ${topic} - Exclusive Offer Inside!`,
        `Last Chance: ${topic} ends tonight`,
        `You asked, we delivered: ${topic}`,
        `💰 Save big on ${topic}`,
        `Flash Sale: ${topic} at 50% off`,
        `Your VIP access to ${topic}`,
        `Don't miss out on ${topic}`,
        `🔥 Hot deal: ${topic}`,
        `Special for you: ${topic}`,
        `Limited spots: ${topic}`
      ],
      newsletter: [
        `This week in ${topic}`,
        `Your ${topic} digest is here`,
        `📰 ${topic}: What you need to know`,
        `Inside: Everything about ${topic}`,
        `${topic} tips you can't miss`,
        `The ${topic} edition`,
        `Fresh insights on ${topic}`,
        `Your weekly ${topic} fix`,
        `🌟 ${topic} highlights`,
        `Breaking: ${topic} updates`
      ],
      educational: [
        `How to master ${topic}`,
        `The ultimate guide to ${topic}`,
        `${topic}: Everything you need to know`,
        `📚 Learn ${topic} in 5 minutes`,
        `Pro tips for ${topic}`,
        `The secret to ${topic}`,
        `${topic} hacks you need`,
        `Master ${topic} today`,
        `🎓 ${topic} 101`,
        `Advanced ${topic} strategies`
      ],
      engagement: [
        `Quick question about ${topic}`,
        `What do you think about ${topic}?`,
        `Help us improve ${topic}`,
        `Your opinion on ${topic} matters`,
        `🙋 ${topic} - yes or no?`,
        `We need your feedback on ${topic}`,
        `Tell us about your ${topic} experience`,
        `Poll: ${topic}`,
        `💬 Let's talk about ${topic}`,
        `Your thoughts on ${topic}?`
      ],
      urgency: [
        `⏰ Ending soon: ${topic}`,
        `Last call for ${topic}`,
        `Hurry! ${topic} expires`,
        `Final hours: ${topic}`,
        `Today only: ${topic}`,
        `⚡ Flash: ${topic}`,
        `Almost gone: ${topic}`,
        `Last chance for ${topic}`,
        `Don't wait: ${topic}`,
        `Time-sensitive: ${topic}`
      ]
    };

    const output = `
# EMAIL SUBJECT LINES
## Topic: ${topic}
## Type: ${type}

---

### Generated Subject Lines

${templates[type]?.map((s, i) => `${i + 1}. ${s}`).join('\n')}

---

## BEST PRACTICES

✅ **Do:**
- Keep under 50 characters for mobile
- Use personalization when possible
- Create urgency without being spammy
- A/B test different approaches
- Match subject to email content

❌ **Don't:**
- Use all caps (looks spammy)
- Overuse exclamation marks!!!
- Make false promises
- Use spam trigger words excessively
- Forget mobile preview

---

## PERFORMANCE TIPS

- **Open Rate Benchmark:** 15-25% is average
- **Best Send Times:** Tuesday-Thursday, 10am-2pm
- **Personalization:** Adds 26% higher open rates
- **Emoji Use:** Can increase opens by 56%

---

*Generated by Abetworks Email Subject Line Generator*
`.trim();

    setSubjects(output);
  };

  return (
    <ToolWrapper
      title="Email Subject Line Generator"
      description="Create compelling email subject lines that boost open rates"
      icon="📧"
      inputValue={topic}
      outputValue={subjects}
      outputLabel="Subject Lines"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-email-subjects.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Email Topic/Content *</label>
          <input
            type="text"
            className="form-control"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g., Summer sale, Newsletter, Product launch"
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Email Type</label>
          <select className="form-select" value={type} onChange={(e) => setType(e.target.value)}>
            <option value="promotional">Promotional</option>
            <option value="newsletter">Newsletter</option>
            <option value="educational">Educational</option>
            <option value="engagement">Engagement</option>
            <option value="urgency">Urgency/FOMO</option>
          </select>
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>📧 Generate Subject Lines</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Email Subject Line Generator" compact /></div>
    </ToolWrapper>
  );
};

export default EmailSubjectLineGenerator;
