import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const InstagramCaptionGenerator: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [style, setStyle] = useState('casual');
  const [captions, setCaptions] = useState('');

  const generate = () => {
    if (!topic.trim()) return;

    const templates: Record<string, string[]> = {
      casual: [
        `Just another day of ${topic} ✨`,
        `Living for these ${topic} moments 💕`,
        `${topic} kind of mood`,
        `Can't get enough of ${topic}`,
        `Currently obsessed with ${topic}`,
        `${topic} vibes only`,
        `This is what ${topic} looks like`,
        `Found my happy place: ${topic}`,
        `Doing more of what makes me happy: ${topic}`,
        `${topic} = life goals`
      ],
      inspirational: [
        `Dream big, ${topic} bigger ✨`,
        `Every ${topic} session brings me closer to my goals`,
        `Believe in the power of ${topic}`,
        `Your only limit is you. Keep ${topic}ing`,
        `Success is ${topic} + consistency`,
        `The best investment? Time spent on ${topic}`,
        `Be the reason someone believes in ${topic}`,
        `Great things happen to those who ${topic}`,
        `Stay focused on your ${topic} journey`,
        `Your ${topic} story matters`
      ],
      funny: [
        `I put the 'pro' in procrastinate... but at least I'm good at ${topic} 😅`,
        `${topic}: Because adulting is hard`,
        `My therapist said I need to talk about my feelings... so here's a ${topic} post instead`,
        `I'm not lazy, I'm just on ${topic} energy saving mode`,
        `${topic} is my cardio`,
        `Warning: May spontaneously ${topic}`,
        `I came, I saw, I ${topic}'d`,
        `${topic} because wine was too expensive`,
        `Not all who wander are lost... some are just ${topic}ing`,
        `Plot twist: I actually know what I'm doing with ${topic} (jk)`
      ],
      engagement: [
        `Drop a 🔥 if you love ${topic} too!`,
        `Tag someone who needs to see this ${topic} content`,
        `Double tap if you agree! 💕`,
        `What's your favorite thing about ${topic}? Comment below! 👇`,
        `Save this for later! 📌 ${topic} tips`,
        `Share with a friend who loves ${topic}!`,
        `Would you try this? Yes or no? ${topic}`,
        `Tell me I'm not the only one who ${topic}s`,
        `First to comment gets... my eternal gratitude! ${topic}`,
        `Swipe for more ${topic} inspiration! 👉`
      ],
      business: [
        `New arrival! ${topic} now available 🛒`,
        `Limited stock! Get yours before it's gone ${topic}`,
        `Flash sale! ${topic} at 50% off - today only!`,
        `Behind the scenes of our ${topic} process`,
        `Customer favorite! ⭐⭐⭐⭐⭐ ${topic}`,
        `Just dropped! Check out our latest ${topic}`,
        `Pre-order now! ${topic} launching soon`,
        `Thank you for the love on our ${topic}! 🙏`,
        `Sneak peek! Coming soon: ${topic}`,
        `Last chance! ${topic} sale ends tonight`
      ]
    };

    const emojiSets: Record<string, string[]> = {
      casual: ['✨', '💕', '🌟', '😊', '🎉', '🔥', '💫', '🌈', '💖', '🎊'],
      inspirational: ['✨', '💪', '🌟', '🎯', '💫', '🚀', '💖', '🏆', '🌈', '⭐'],
      funny: ['😂', '🤣', '😅', '🙃', '😜', '🤪', '😎', '👀', '💀', '🎭'],
      engagement: ['👇', '🔥', '💕', '📌', '👉', '👈', '❓', '💬', '🙌', '✨'],
      business: ['🛒', '⭐', '🔥', '💰', '🎉', '📦', '🚚', '💎', '🏷️', '🎁']
    };

    const emojis = emojiSets[style];
    
    const output = `
# INSTAGRAM CAPTIONS
## Topic: ${topic}
## Style: ${style}

---

### Generated Captions

${templates[style]?.map((c, i) => `${i + 1}. ${c} ${emojis[i % emojis.length]}`).join('\n')}

---

## HASHTAG SUGGESTIONS

#${topic.replace(/\s/g, '')} #instagood #photooftheday #love #happy #trending #viral #explore #fyp #instadaily

---

## INSTAGRAM TIPS

✅ **Caption Best Practices:**
- First line should hook attention
- Use line breaks for readability
- Include a CTA (call-to-action)
- Add relevant emojis
- Keep some captions short & punchy

📊 **Posting Tips:**
- Best times: 9-11am, 1-3pm (varies by audience)
- Use all 30 hashtags strategically
- Post to Stories within 1 hour of feed post
- Engage with comments in first hour
- Use location tags when relevant

📱 **Format Tips:**
- Use emoji breaks between sections
- Put important info first (preview text)
- Add spacing for mobile readability
- Consider caption length (2,200 char max)

---

*Generated by Abetworks Instagram Caption Generator*
`.trim();

    setCaptions(output);
  };

  return (
    <ToolWrapper
      title="Instagram Caption Generator"
      description="Create engaging Instagram captions that boost likes and comments"
      icon="📸"
      inputValue={topic}
      outputValue={captions}
      outputLabel="Captions"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-instagram-captions.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Post Topic/Content *</label>
          <input
            type="text"
            className="form-control"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g., beach vacation, new product, workout"
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Caption Style</label>
          <select className="form-select" value={style} onChange={(e) => setStyle(e.target.value)}>
            <option value="casual">Casual/Friendly</option>
            <option value="inspirational">Inspirational</option>
            <option value="funny">Funny/Witty</option>
            <option value="engagement">Engagement-Focused</option>
            <option value="business">Business/Promotional</option>
          </select>
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>📸 Generate Captions</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Instagram Caption Generator" compact /></div>
    </ToolWrapper>
  );
};

export default InstagramCaptionGenerator;
