import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

// Generic generator for remaining marketing tools
const MarketingToolGenerator: React.FC<{ toolName: string; icon: string; description: string; placeholder: string; generateFn: (input: string) => string }> = ({ toolName, icon, description, placeholder, generateFn }) => {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');

  const handleGenerate = () => {
    const result = generateFn(input);
    setOutput(result);
  };

  return (
    <ToolWrapper
      title={toolName}
      description={description}
      icon={icon}
      inputValue={input}
      outputValue={output}
      outputLabel="Output"
      showCopy={true}
      showDownload={true}
      downloadFilename={`${toolName.toLowerCase().replace(/\s/g, '-')}.md`}
    >
      <div className="mb-3">
        <label className="form-label">Enter your input:</label>
        <textarea
          className="form-control"
          rows={4}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder={placeholder}
        />
      </div>
      <button className="btn btn-primary btn-lg" onClick={handleGenerate}>{icon} Generate</button>
      <div className="mt-4"><LeadCaptureForm toolName={toolName} compact /></div>
    </ToolWrapper>
  );
};

// Landing Page Copy Generator
const LandingPageCopyGenerator: React.FC = () => {
  const [productName, setProductName] = useState('');
  const [features, setFeatures] = useState('');
  const [audience, setAudience] = useState('');
  const [copy, setCopy] = useState('');

  const generate = () => {
    const name = productName || 'Product';
    const featureList = features.split('\n').filter(f => f.trim());
    const targetAudience = audience || 'your target audience';

    const output = `
# LANDING PAGE COPY
## ${name.toUpperCase()}

---

## HERO SECTION

**Headline:** Transform Your ${targetAudience === 'your target audience' ? 'Life' : audience} with ${name}

**Subheadline:** The all-in-one solution that helps ${targetAudience} achieve their goals faster, easier, and more effectively.

**CTA Button:** Get Started Free

---

## PROBLEM SECTION

### Are You Struggling With...

- Feeling overwhelmed by complexity?
- Wasting time on solutions that don't work?
- Missing out on results you deserve?

You're not alone. ${featureList.length > 0 ? featureList.length : 'Many'} common challenges hold ${targetAudience} back every day.

---

## SOLUTION SECTION

### Introducing ${name}

${name} is designed specifically for ${targetAudience} who want real results.

${featureList.map(f => `✅ **${f.split(':')[0] || f}**`).join('\n')}

---

## BENEFITS SECTION

### Why Choose ${name}?

🚀 **Fast Results** - See improvements in days, not months

💎 **Premium Quality** - Built with the best standards

🔒 **Secure & Reliable** - Your data is protected

💬 **24/7 Support** - We're here whenever you need us

---

## SOCIAL PROOF

### What Our Customers Say

⭐⭐⭐⭐⭐

"${name} completely transformed how I work. I can't imagine going back!"
- Happy Customer

⭐⭐⭐⭐⭐

"Best investment I've made this year. Highly recommend!"
- Satisfied User

---

## CTA SECTION

### Ready to Get Started?

Join thousands of satisfied customers who've transformed their ${targetAudience === 'your target audience' ? 'lives' : 'workflow'} with ${name}.

**Primary CTA:** Start Your Free Trial

**Secondary CTA:** Schedule a Demo

**Risk Reversal:** 30-day money-back guarantee. No questions asked.

---

## FAQ SECTION

### Frequently Asked Questions

**Q: Is there a free trial?**
A: Yes! We offer a 14-day free trial with full access.

**Q: Can I cancel anytime?**
A: Absolutely. No contracts, cancel anytime.

**Q: Do you offer refunds?**
A: Yes, 30-day money-back guarantee.

---

*Generated by Abetworks Landing Page Copy Generator*
`.trim();

    setCopy(output);
  };

  return (
    <ToolWrapper
      title="Landing Page Copy Generator"
      description="Create high-converting landing page copy with proven frameworks"
      icon="📄"
      inputValue={productName}
      outputValue={copy}
      outputLabel="Landing Page Copy"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-landing-page-copy.md"
    >
      <div className="row g-3">
        <div className="col-md-6">
          <label className="form-label">Product/Service Name *</label>
          <input type="text" className="form-control" value={productName} onChange={(e) => setProductName(e.target.value)} placeholder="e.g., TaskMaster Pro" />
        </div>
        <div className="col-md-6">
          <label className="form-label">Target Audience</label>
          <input type="text" className="form-control" value={audience} onChange={(e) => setAudience(e.target.value)} placeholder="e.g., Busy professionals" />
        </div>
        <div className="col-12">
          <label className="form-label">Key Features (one per line)</label>
          <textarea className="form-control" rows={4} value={features} onChange={(e) => setFeatures(e.target.value)} placeholder="Easy to use&#10;Fast setup&#10;Great support" />
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>📄 Generate Copy</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Landing Page Copy Generator" compact /></div>
    </ToolWrapper>
  );
};

export default LandingPageCopyGenerator;
export { MarketingToolGenerator };
