import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const LinkedInPostGenerator: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [type, setType] = useState('insight');
  const [posts, setPosts] = useState('');

  const generate = () => {
    if (!topic.trim()) return;

    const templates: Record<string, string[]> = {
      insight: [
        `After years in the industry, here's what I've learned about ${topic}:\n\n[Share your insight]\n\nWhat's your experience?`,
        `Unpopular opinion: ${topic} is overrated.\n\nHere's why...\n\n[Explain your reasoning]`,
        `The biggest mistake I see with ${topic}:\n\n[Describe the mistake]\n\nHere's how to fix it:`,
        `Hot take on ${topic}:\n\n[Share your perspective]\n\nAgree or disagree?`,
        `I used to think ${topic} was simple.\n\nI was wrong.\n\nHere's what I learned:`
      ],
      story: [
        `5 years ago, I knew nothing about ${topic}.\n\nToday, [share your achievement].\n\nHere's my journey:`,
        `The day everything changed for me was when I discovered ${topic}.\n\n[Tell your story]`,
        `I almost gave up on ${topic}.\n\nThen something happened...\n\n[Share the turning point]`,
        `My biggest failure with ${topic} taught me:\n\n[Share the lesson]\n\nWhat's your biggest lesson?`,
        `From zero to hero: My ${topic} transformation\n\n[Share your story in detail]`
      ],
      educational: [
        `Everything you need to know about ${topic}:\n\n📌 Point 1\n📌 Point 2\n📌 Point 3\n📌 Point 4\n📌 Point 5\n\nSave this for later!`,
        `${topic} 101: A thread 🧵\n\n1/ Let's start with the basics...`,
        `3 ${topic} tips that changed my career:\n\n1️⃣ [Tip 1]\n2️⃣ [Tip 2]\n3️⃣ [Tip 3]\n\nWhich resonates most?`,
        `The complete guide to ${topic}:\n\n✅ Step 1\n✅ Step 2\n✅ Step 3\n\nBookmark this!`,
        `Common ${topic} questions, answered:\n\nQ: [Question 1]\nA: [Answer]\n\nQ: [Question 2]\nA: [Answer]`
      ],
      promotional: [
        `Excited to announce [something related to ${topic}]!\n\n[Details about your offering]\n\nDM me to learn more.`,
        `We just launched something special for ${topic} enthusiasts.\n\n[Describe your product/service]\n\nLink in comments 👇`,
        `Thrilled to share that [achievement related to ${topic}]!\n\nThank you to everyone who supported this journey.`,
        `New resource alert! 🚨\n\n[Describe what you created for ${topic}]\n\nGrab it here: [link]`,
        `Limited spots available for [${topic} related offering]!\n\n[Details]\n\nComment "interested" to learn more.`
      ],
      engagement: [
        `Question for my network:\n\nWhat's your biggest challenge with ${topic}?\n\nLet's discuss in the comments! 👇`,
        `Poll time! 📊\n\nWhen it comes to ${topic}, what's your approach?\n\nA) [Option 1]\nB) [Option 2]\nC) [Option 3]\nD) Other (comment below)`,
        `Looking for recommendations:\n\nWhat's your favorite tool/resource for ${topic}?\n\nSharing is caring! 💙`,
        `Unpopular opinion: ${topic}\n\nChange my mind. 🪑`,
        `What's one thing you wish you knew earlier about ${topic}?\n\nI'll start: [Your answer]\n\nYour turn!`
      ]
    };

    const output = `
# LINKEDIN POST IDEAS
## Topic: ${topic}
## Type: ${type}

---

### Generated Posts

${templates[type]?.map((p, i) => `**Post ${i + 1}:**\n\n${p}\n\n---`).join('\n')}

---

## LINKEDIN BEST PRACTICES

✅ **Content Tips:**
- Hook in the first 2-3 lines (before "see more")
- Use white space for readability
- Add relevant hashtags (3-5)
- Include a clear CTA
- Post during business hours

📊 **Engagement Tips:**
- Respond to all comments in first 2 hours
- Tag relevant people/companies (sparingly)
- Use native video when possible
- Share personal stories and lessons
- Provide genuine value

⏰ **Optimal Posting Times:**
- Tuesday-Thursday: 8-10am, 12pm, 5-6pm
- Monday/Friday: Slightly lower engagement
- Weekend: Lower overall activity

---

## HASHTAG SUGGESTIONS

#${topic.replace(/\s/g, '')} #linkedin #professional #career #business #industry #growth #leadership #networking

---

*Generated by Abetworks LinkedIn Post Generator*
`.trim();

    setPosts(output);
  };

  return (
    <ToolWrapper
      title="LinkedIn Post Generator"
      description="Create professional LinkedIn posts that drive engagement and build your brand"
      icon="💼"
      inputValue={topic}
      outputValue={posts}
      outputLabel="LinkedIn Posts"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-linkedin-posts.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Topic/Subject *</label>
          <input
            type="text"
            className="form-control"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g., leadership, career growth, industry trend"
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Post Type</label>
          <select className="form-select" value={type} onChange={(e) => setType(e.target.value)}>
            <option value="insight">Industry Insight</option>
            <option value="story">Personal Story</option>
            <option value="educational">Educational/How-To</option>
            <option value="promotional">Promotional</option>
            <option value="engagement">Engagement/Question</option>
          </select>
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>💼 Generate Posts</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="LinkedIn Post Generator" compact /></div>
    </ToolWrapper>
  );
};

export default LinkedInPostGenerator;
