import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const MarketingFunnelBuilder: React.FC = () => {
  const [businessType, setBusinessType] = useState('');
  const [product, setProduct] = useState('');
  const [funnel, setFunnel] = useState('');

  const generate = () => {
    const business = businessType || 'Business';
    const prod = product || 'Product/Service';

    const output = `
# MARKETING FUNNEL STRATEGY
## ${business.toUpperCase()} - ${prod.toUpperCase()}

---

## FUNNEL OVERVIEW

        AWARENESS
           ↓
        INTEREST
           ↓
        CONSIDERATION
           ↓
        INTENT
           ↓
        PURCHASE
           ↓
        RETENTION

---

## STAGE 1: AWARENESS (Top of Funnel)

### Goal: Attract strangers and make them aware of their problem

**Content Types:**
- Blog posts about ${business} challenges
- Social media educational content
- YouTube tutorials
- Podcast appearances
- Infographics

**Metrics to Track:**
- Website traffic
- Social media reach
- Brand mentions
- Content shares

**Sample Content:**
- "10 Common ${business} Mistakes"
- "The Ultimate Guide to ${prod}"
- "What is ${prod} and Do You Need It?"

---

## STAGE 2: INTEREST (Middle of Funnel)

### Goal: Capture leads and nurture interest

**Content Types:**
- Lead magnets (ebooks, checklists)
- Email newsletter
- Webinars
- Case studies
- Comparison guides

**Metrics to Track:**
- Email signups
- Lead magnet downloads
- Email open rates
- Time on page

**Lead Magnet Ideas:**
- "${prod} Buyer's Checklist"
- "Free ${business} Assessment"
- "${prod} ROI Calculator"

---

## STAGE 3: CONSIDERATION (Middle of Funnel)

### Goal: Help prospects evaluate solutions

**Content Types:**
- Product demos
- Free trials
- Detailed comparisons
- Customer testimonials
- Expert reviews

**Metrics to Track:**
- Demo requests
- Trial signups
- Feature page views
- Pricing page visits

**Sample Content:**
- "${prod} vs Competitors"
- "How ${prod} Solves [Problem]"
- Customer success stories

---

## STAGE 4: INTENT (Bottom of Funnel)

### Goal: Convert interested prospects to buyers

**Content Types:**
- Sales pages
- Limited-time offers
- Consultation calls
- Live demos
- ROI calculators

**Metrics to Track:**
- Add to cart rate
- Checkout initiation
- Sales calls booked
- Quote requests

**Conversion Tactics:**
- Scarcity (limited spots/time)
- Social proof (reviews, testimonials)
- Risk reversal (guarantees)
- Bonuses for acting now

---

## STAGE 5: PURCHASE (Conversion)

### Goal: Complete the sale smoothly

**Optimization Tips:**
- Simplify checkout process
- Multiple payment options
- Clear return policy
- Order confirmation emails
- Upsell/cross-sell offers

**Metrics to Track:**
- Conversion rate
- Cart abandonment rate
- Average order value
- Customer acquisition cost

---

## STAGE 6: RETENTION (Post-Purchase)

### Goal: Turn customers into advocates

**Strategies:**
- Onboarding emails
- Customer support excellence
- Loyalty programs
- Referral incentives
- Regular check-ins

**Metrics to Track:**
- Customer lifetime value
- Repeat purchase rate
- Net Promoter Score
- Churn rate

**Sample Campaigns:**
- Welcome series
- Usage tips emails
- Anniversary rewards
- Referral program invites

---

## FUNNEL METRICS DASHBOARD

| Stage | Metric | Target | Current |
|-------|--------|--------|---------|
| Awareness | Monthly visitors | 10,000 | - |
| Interest | Email subscribers | 2,000 | - |
| Consideration | Demo requests | 200 | - |
| Intent | Sales calls | 50 | - |
| Purchase | Customers | 25 | - |
| Retention | Repeat rate | 40% | - |

---

## IMPLEMENTATION TIMELINE

**Week 1-2:** Set up awareness content
**Week 3-4:** Create lead magnets
**Week 5-6:** Build email sequences
**Week 7-8:** Optimize conversion pages
**Week 9-10:** Implement retention campaigns

---

*Generated by Abetworks Marketing Funnel Builder*
`.trim();

    setFunnel(output);
  };

  return (
    <ToolWrapper
      title="Marketing Funnel Builder"
      description="Create a complete marketing funnel strategy for your business"
      icon="🌪️"
      inputValue={businessType}
      outputValue={funnel}
      outputLabel="Marketing Funnel"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-marketing-funnel.md"
    >
      <div className="row g-3">
        <div className="col-md-6">
          <label className="form-label">Business Type *</label>
          <input type="text" className="form-control" value={businessType} onChange={(e) => setBusinessType(e.target.value)} placeholder="e.g., SaaS, E-commerce, Coaching" />
        </div>
        <div className="col-md-6">
          <label className="form-label">Main Product/Service *</label>
          <input type="text" className="form-control" value={product} onChange={(e) => setProduct(e.target.value)} placeholder="e.g., Project management software" />
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>🌪️ Build Funnel</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Marketing Funnel Builder" compact /></div>
    </ToolWrapper>
  );
};

export default MarketingFunnelBuilder;
