import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const SocialMediaPostGenerator: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [platform, setPlatform] = useState('instagram');
  const [tone, setTone] = useState('friendly');
  const [posts, setPosts] = useState('');

  const generate = () => {
    if (!topic.trim()) return;

    const templates: Record<string, string[]> = {
      instagram: [
        `📸 ${topic}\n\nDouble tap if you agree! 💕\n\n#${topic.replace(/\s/g, '')} #instagood #photooftheday`,
        `✨ Just discovered something amazing about ${topic}!\n\nSwipe to learn more 👉\n\n#${topic.replace(/\s/g, '')} #lifestyle`,
        `💭 Question for you: What's your experience with ${topic}?\n\nDrop a comment below! 👇\n\n#${topic.replace(/\s/g, '')} #community`,
        `🎯 3 tips about ${topic}:\n\n1️⃣ First tip here\n2️⃣ Second tip here  \n3️⃣ Third tip here\n\nSave this for later! 📌\n\n#${topic.replace(/\s/g, '')} #tips`,
        `🔥 Behind the scenes of ${topic}\n\nThis is what really happens...\n\n#${topic.replace(/\s/g, '')} #bts`
      ],
      twitter: [
        `🧵 Thread: Everything you need to know about ${topic}\n\n1/ Let's dive in...`,
        `Hot take: ${topic} is underrated.\n\nHere's why 👇`,
        `Just published: My thoughts on ${topic}\n\nRead more → [link]`,
        `Unpopular opinion about ${topic}: 🪑\n\nChange my mind.`,
        `Reminder: ${topic} takes time.\n\nBe patient with yourself. 💙`
      ],
      linkedin: [
        `💼 Professional insights on ${topic}:\n\nIn my experience, here's what works...\n\n#${topic.replace(/\s/g, '')} #professional #career`,
        `🎓 Lesson learned about ${topic}:\n\n[Share your story]\n\nWhat's your experience?\n\n#${topic.replace(/\s/g, '')} #leadership`,
        `📊 Industry update: ${topic}\n\nKey takeaways:\n• Point 1\n• Point 2\n• Point 3\n\n#${topic.replace(/\s/g, '')} #industry`,
        `🤝 Grateful to share that...\n\n${topic} has been a game-changer.\n\n#${topic.replace(/\s/g, '')} #grateful #growth`,
        `💡 Innovation in ${topic}:\n\nThe future is here. Here's what's next...\n\n#${topic.replace(/\s/g, '')} #innovation`
      ],
      facebook: [
        `📢 Exciting news about ${topic}!\n\nTag someone who needs to see this! 👇`,
        `🎉 We're celebrating ${topic}!\n\nJoin us in the comments!\n\n#${topic.replace(/\s/g, '')}`,
        `❓ Quick poll: What do you think about ${topic}?\n\nVote in the comments!`,
        `📝 Blog post: ${topic}\n\nRead the full article: [link]\n\n#${topic.replace(/\s/g, '')}`,
        `🙏 Thank you for ${topic}!\n\nWe appreciate our amazing community!`
      ]
    };

    const toneModifiers: Record<string, string> = {
      friendly: 'Keep it warm and approachable',
      professional: 'Maintain a business-appropriate tone',
      humorous: 'Add jokes and wit where appropriate',
      inspirational: 'Focus on motivation and positivity',
      educational: 'Emphasize learning and value'
    };

    const platformPosts = templates[platform] || templates.instagram;
    
    const output = `
# SOCIAL MEDIA POSTS FOR ${platform.toUpperCase()}
## Topic: ${topic}
## Tone: ${tone} (${toneModifiers[tone]})

---

${platformPosts.map((p, i) => `### Post Option ${i + 1}\n\n${p}\n\n---`).join('\n')}

## BEST PRACTICES FOR ${platform.toUpperCase()}

${platform === 'instagram' ? `- Post consistently (1-2 times daily)
- Use high-quality visuals
- Engage with comments within 1 hour
- Use Stories for behind-the-scenes
- Leverage Reels for reach` : platform === 'twitter' ? `- Tweet 3-5 times daily
- Use threads for longer content
- Engage with trending topics
- Reply to comments quickly
- Use images/videos for engagement` : platform === 'linkedin' ? `- Post during business hours
- Share professional insights
- Engage thoughtfully with comments
- Use native video when possible
- Write long-form for thought leadership` : `- Post when your audience is active
- Use engaging visuals
- Ask questions to drive comments
- Share valuable content
- Respond to all comments`}

---

*Generated by Abetworks Social Media Post Generator*
`.trim();

    setPosts(output);
  };

  return (
    <ToolWrapper
      title="Social Media Post Generator"
      description="Create engaging social media posts for any platform in seconds"
      icon="📱"
      inputValue={topic}
      outputValue={posts}
      outputLabel="Generated Posts"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-social-posts.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Topic/Subject *</label>
          <input
            type="text"
            className="form-control"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g., New product launch, Fitness tips"
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Platform</label>
          <select className="form-select" value={platform} onChange={(e) => setPlatform(e.target.value)}>
            <option value="instagram">Instagram</option>
            <option value="twitter">Twitter/X</option>
            <option value="linkedin">LinkedIn</option>
            <option value="facebook">Facebook</option>
            <option value="tiktok">TikTok</option>
          </select>
        </div>
        <div className="col-md-6">
          <label className="form-label">Tone</label>
          <select className="form-select" value={tone} onChange={(e) => setTone(e.target.value)}>
            <option value="friendly">Friendly</option>
            <option value="professional">Professional</option>
            <option value="humorous">Humorous</option>
            <option value="inspirational">Inspirational</option>
            <option value="educational">Educational</option>
          </select>
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>📱 Generate Posts</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Social Media Post Generator" compact /></div>
    </ToolWrapper>
  );
};

export default SocialMediaPostGenerator;
