import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const TweetGenerator: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [type, setType] = useState('general');
  const [tweets, setTweets] = useState('');

  const generate = () => {
    if (!topic.trim()) return;

    const templates: Record<string, string[]> = {
      general: [
        `Just discovered something amazing about ${topic}. Game changer! 🚀`,
        `Hot take: ${topic} is underrated. Here's why... 🧵`,
        `Unpopular opinion: ${topic} isn't what you think it is.`,
        `If you're not paying attention to ${topic}, you're missing out.`,
        `${topic} in 2024 be like... 😅`,
        `Reminder: ${topic} takes time. Be patient with yourself. 💙`,
        `The best investment you can make? ${topic}.`,
        `Nobody:\nAbsolutely nobody:\nMe: *thinks about ${topic}*`,
        `Plot twist: ${topic} is actually simple.`,
        `I could talk about ${topic} for hours. Send help. 😂`
      ],
      thread: [
        `🧵 Thread: Everything you need to know about ${topic}\n\n1/ Let's dive in...`,
        `I spent 100 hours researching ${topic}.\n\nHere are the top 10 insights:\n\n🧵 1/10`,
        `${topic} explained in 10 tweets:\n\n🧵 1/10`,
        `The ultimate guide to ${topic}:\n\nBookmark this thread 🔖\n\n1/`,
        `5 lessons from ${topic} that changed my perspective:\n\n🧵 1/5`
      ],
      question: [
        `Quick question: What's your experience with ${topic}?`,
        `Poll: Do you prefer A or B when it comes to ${topic}?`,
        `What's the biggest misconception about ${topic}?`,
        `Looking for recommendations: Best resources for ${topic}?`,
        `Real question: Is ${topic} worth the hype?`,
        `Who else is guilty of ${topic}? 🙋`,
        `What's your hot take on ${topic}?`,
        `Serious: What's one thing you wish you knew about ${topic} earlier?`
      ],
      promotional: [
        `🚀 Just launched! [Something about ${topic}]\n\nCheck it out: [link]`,
        `Big news! We're changing how people think about ${topic}.\n\nLearn more: [link]`,
        `Limited time: Get [something related to ${topic}] at 50% off!\n\nGrab it: [link]`,
        `New blog post: ${topic} - Everything you need to know\n\nRead: [link]`,
        `We hit a milestone! Thank you for being part of our ${topic} journey! 🎉`
      ],
      engagement: [
        `Drop a 🔥 if you agree! ${topic}`,
        `RT if you've ever ${topic}'d`,
        `Tag someone who needs to hear this about ${topic}`,
        `Quote tweet with your take on ${topic}`,
        `First 10 people to like this get [something about ${topic}]`,
        `Let's settle this: ${topic} - yes or no?`
      ]
    };

    const output = `
# TWEET IDEAS
## Topic: ${topic}
## Type: ${type}

---

### Generated Tweets

${templates[type]?.map((t, i) => `${i + 1}. ${t}`).join('\n\n')}

---

## TWITTER BEST PRACTICES

✅ **Tweet Tips:**
- Keep it under 280 characters (obviously)
- Use 1-2 relevant hashtags max
- Add images/videos for 2x engagement
- Post threads for longer content
- Engage with replies quickly

📊 **Growth Tips:**
- Tweet 3-5 times daily
- Reply to bigger accounts in your niche
- Use trending topics strategically
- Post at optimal times (8-10am, 6-9pm)
- Pin your best tweet

🧵 **Thread Tips:**
- Hook in the first tweet
- Number your tweets (1/10)
- Add value in each tweet
- End with a CTA or summary
- Ask for RTs/bookmarks

---

## HASHTAG SUGGESTIONS

#${topic.replace(/\s/g, '')} #Twitter #Trending #Viral #Thread

---

*Generated by Abetworks Tweet Generator*
`.trim();

    setTweets(output);
  };

  return (
    <ToolWrapper
      title="Tweet Generator"
      description="Create engaging tweets and threads that get likes, retweets, and replies"
      icon="🐦"
      inputValue={topic}
      outputValue={tweets}
      outputLabel="Tweet Ideas"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-tweets.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Topic *</label>
          <input
            type="text"
            className="form-control"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g., AI, productivity, startup life"
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Tweet Type</label>
          <select className="form-select" value={type} onChange={(e) => setType(e.target.value)}>
            <option value="general">General Tweet</option>
            <option value="thread">Thread Starter</option>
            <option value="question">Question/Poll</option>
            <option value="promotional">Promotional</option>
            <option value="engagement">Engagement Bait</option>
          </select>
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>🐦 Generate Tweets</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="Tweet Generator" compact /></div>
    </ToolWrapper>
  );
};

export default TweetGenerator;
