import React, { useState } from 'react';
import ToolWrapper from '../../components/ToolWrapper';
import LeadCaptureForm from '../../components/LeadCaptureForm';

const YouTubeTitleGenerator: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [style, setStyle] = useState('viral');
  const [titles, setTitles] = useState('');

  const generate = () => {
    if (!topic.trim()) return;

    const templates: Record<string, string[]> = {
      viral: [
        `I Tried ${topic} for 30 Days - Here's What Happened`,
        `The ${topic} Experiment That Broke the Internet`,
        `Why Everyone Is Talking About ${topic}`,
        `${topic} Gone Wrong! (You Won't Believe This)`,
        `The Truth About ${topic} Nobody Tells You`,
        `I Spent $1000 on ${topic} - Was It Worth It?`,
        `${topic}: The Video That Will Change Everything`,
        `This ${topic} Hack Got 1 Million Views`,
        `The Most Extreme ${topic} Challenge Ever`,
        `${topic} vs ${topic}: Epic Showdown`
      ],
      tutorial: [
        `${topic} Tutorial for Beginners (Step by Step)`,
        `How to ${topic} - Complete Guide 2024`,
        `${topic} Masterclass: Learn Everything`,
        `The Only ${topic} Tutorial You'll Ever Need`,
        `${topic} Explained in 10 Minutes`,
        `Learn ${topic} Fast - Quick Tutorial`,
        `${topic} Basics: Start Here`,
        `Advanced ${topic} Techniques`,
        `${topic} Tips and Tricks`,
        `Professional ${topic} Workflow`
      ],
      review: [
        `${topic} Review - Is It Worth It?`,
        `Honest ${topic} Review After 6 Months`,
        `${topic} Review: The Good, Bad, and Ugly`,
        `Don't Buy ${topic} Until You Watch This`,
        `${topic} Unboxing and First Impressions`,
        `Full ${topic} Review + Demo`,
        `${topic} Long-Term Review`,
        `Why I Stopped Using ${topic} - Review`,
        `${topic} Review: Better Than Expected?`,
        `Brutally Honest ${topic} Review`
      ],
      listicle: [
        `10 Best ${topic} Tips You Need to Know`,
        `7 ${topic} Mistakes Everyone Makes`,
        `15 ${topic} Hacks That Actually Work`,
        `5 ${topic} Tools I Can't Live Without`,
        `20 ${topic} Facts That Will Shock You`,
        `12 ${topic} Trends Taking Over`,
        `8 ${topic} Secrets Professionals Use`,
        `25 ${topic} Ideas for Inspiration`,
        `9 ${topic} Myths Debunked`,
        `30 ${topic} Resources You Need`
      ],
      storytime: [
        `My ${topic} Journey - The Full Story`,
        `How ${topic} Changed My Life`,
        `The Day Everything Changed with ${topic}`,
        `Why I Quit My Job to Focus on ${topic}`,
        `My Biggest ${topic} Failure`,
        `From Zero to Hero: My ${topic} Story`,
        `The ${topic} Mistake That Cost Me Everything`,
        `How I Made $10K with ${topic}`,
        `My ${topic} Transformation Story`,
        `The Real Reason I Started ${topic}`
      ]
    };

    const output = `
# YOUTUBE TITLE IDEAS
## Topic: ${topic}
## Style: ${style}

---

### Generated Titles

${templates[style]?.map((t, i) => `${i + 1}. ${t}`).join('\n')}

---

## YOUTUBE SEO TIPS

✅ **Title Best Practices:**
- Keep under 60 characters (mobile display)
- Put important keywords first
- Use numbers and power words
- Create curiosity gap
- Match search intent

📊 **Thumbnail Tips:**
- High contrast, bright colors
- Clear facial expressions
- Minimal text (3-4 words max)
- Consistent branding
- Test different styles

⏱️ **Engagement Tips:**
- Hook viewers in first 15 seconds
- Use chapters for longer videos
- Add end screens and cards
- Respond to comments quickly
- Create playlists

---

## VIRAL TITLE PATTERNS

1. **Transformation:** "From X to Y"
2. **Challenge:** "I Did X for Y Days"
3. **Revelation:** "The Truth About X"
4. **Comparison:** "X vs Y - Surprising Results"
5. **List:** "X Things That Y"

---

*Generated by Abetworks YouTube Title Generator*
`.trim();

    setTitles(output);
  };

  return (
    <ToolWrapper
      title="YouTube Title Generator"
      description="Create click-worthy YouTube titles that boost views and engagement"
      icon="📺"
      inputValue={topic}
      outputValue={titles}
      outputLabel="YouTube Titles"
      showCopy={true}
      showDownload={true}
      downloadFilename="abetworks-youtube-titles.md"
    >
      <div className="row g-3">
        <div className="col-12">
          <label className="form-label">Video Topic *</label>
          <input
            type="text"
            className="form-control"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g., cooking pasta, fitness workout, tech review"
          />
        </div>
        <div className="col-md-6">
          <label className="form-label">Video Style</label>
          <select className="form-select" value={style} onChange={(e) => setStyle(e.target.value)}>
            <option value="viral">Viral/Entertainment</option>
            <option value="tutorial">Tutorial/Educational</option>
            <option value="review">Review/Unboxing</option>
            <option value="listicle">List/Compilation</option>
            <option value="storytime">Storytime/Vlog</option>
          </select>
        </div>
        <div className="col-12">
          <button className="btn btn-primary btn-lg" onClick={generate}>📺 Generate Titles</button>
        </div>
      </div>
      <div className="mt-4"><LeadCaptureForm toolName="YouTube Title Generator" compact /></div>
    </ToolWrapper>
  );
};

export default YouTubeTitleGenerator;
